//// CSS style definitions for Scrumbringer UI.
////
//// Generates all base CSS rules as strings for injection into the page.
//// Includes layout, typography, forms, buttons, and theme variables.

import gleam/string

pub fn base_css() -> String {
  [
    ":root { color-scheme: light dark; }",
    "* { box-sizing: border-box; }",
    "body { margin: 0; font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; background: var(--sb-bg); color: var(--sb-text); }",
    ".app { min-height: 100vh; background: var(--sb-bg); color: var(--sb-text); padding: 16px; }",
    ".page { max-width: 480px; margin: 0 auto; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 16px; }",
    ".admin, .member { display: flex; flex-direction: column; gap: 12px; }",
    ".body { display: flex; gap: 12px; align-items: flex-start; }",
    ".nav { width: 220px; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; display: flex; flex-direction: column; gap: 8px; }",
    ".content { flex: 1; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; min-width: 0; }",
    ".content.pool-main { overflow: hidden; min-height: 520px; }",
    ".pool-layout { display: flex; gap: 12px; align-items: flex-start; width: 100%; }",
    ".pool-main { flex: 1 1 auto; min-width: 0; position: relative; overflow: hidden; }",
    ".pool-right { width: 360px; flex-shrink: 0; position: relative; z-index: 2; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; display: flex; flex-direction: column; gap: 10px; align-self: stretch; }
.pool-my-tasks-dropzone { border: 1px dashed transparent; border-radius: 12px; padding: 8px; transition: border-color 120ms ease, background 120ms ease; min-height: 120px; }
.pool-my-tasks-dropzone.drag-active { border-color: var(--sb-border); background: color-mix(in oklab, var(--sb-elevated) 70%, transparent); }
.pool-my-tasks-dropzone.drop-over { border-color: var(--sb-primary); background: color-mix(in oklab, var(--sb-primary) 12%, var(--sb-elevated)); }
.dropzone-hint { font-size: 12px; color: var(--sb-muted); margin-bottom: 6px; }",
    "@media (max-width: 1280px) { .pool-right { width: 320px; } }
@media (max-width: 1024px) { .pool-layout { flex-direction: column; } .pool-right { width: 100%; } }",
    ".topbar { display: flex; align-items: center; gap: 12px; justify-content: space-between; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; }",
    ".topbar-title { font-weight: 700; }",
    ".topbar-actions { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }",
    ".topbar-group { display: inline-flex; align-items: center; gap: 8px; }",
    ".theme-switch { display: inline-flex; align-items: center; gap: 8px; }",
    ".user { color: var(--sb-muted); }",
    ".section { display: flex; flex-direction: column; gap: 10px; }",
    ".field { display: flex; flex-direction: column; gap: 4px; margin: 8px 0; }",
    ".filters-row { display: flex; gap: 10px; align-items: stretch; flex-wrap: nowrap; overflow-x: auto; padding-bottom: 2px; }",
    ".filters-row .field { margin: 0; min-width: 140px; position: relative; }",
    ".filters-row .field.filter-q { min-width: 180px; }",
    ".filters-row .filter-icon { display: none; font-size: 12px; color: var(--sb-muted); }",
    ".filters-row select, .filters-row input, .filters-row button { height: 36px; }",
    ".filters-row button { padding: 8px 12px; }",
    ".filters-row .filter-tooltip { display: none; position: absolute; left: 0; top: -26px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 999px; padding: 2px 8px; font-size: 12px; color: var(--sb-text); white-space: nowrap; }",
    "@media (max-width: 1024px) { .filters-row { gap: 8px; } .filters-row .filter-label { display: none; } .filters-row .filter-icon { display: inline; } .filters-row .field { min-width: 56px; } .filters-row select, .filters-row input { padding: 6px; } .filters-row .field:hover .filter-tooltip, .filters-row .field:focus-within .filter-tooltip { display: inline-flex; } }",
    ".hint { color: var(--sb-muted); font-size: 0.9em; }",
    ".empty { color: var(--sb-muted); }",
    ".loading { color: var(--sb-info); }",
    ".error { color: var(--sb-danger); }",
    "input, select { padding: 8px; border-radius: 10px; border: 1px solid var(--sb-border); background: var(--sb-elevated); color: var(--sb-text); }",
    "button { padding: 8px 12px; border-radius: 10px; border: 1px solid var(--sb-border); background: var(--sb-elevated); color: var(--sb-text); cursor: pointer; }",
    ".btn-xs { padding: 4px 8px; font-size: 12px; border-radius: 8px; }",
    ".btn-active { border-color: var(--sb-primary); }",
    ".btn-icon { display: inline-flex; align-items: center; justify-content: center; min-width: 28px; min-height: 28px; line-height: 1; position: relative; }",
    ".btn-icon[data-tooltip]::after { content: attr(data-tooltip); display: none; position: absolute; right: 0; top: -28px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 999px; padding: 2px 8px; font-size: 12px; color: var(--sb-text); white-space: nowrap; }",
    ".btn-icon[data-tooltip]:hover::after, .btn-icon[data-tooltip]:focus-visible::after { display: inline-flex; }",
    "button:hover { border-color: var(--sb-primary); }",
    "button:disabled { opacity: 0.6; cursor: not-allowed; }",
    "button[type=\"submit\"] { background: var(--sb-primary); border-color: var(--sb-primary); color: var(--sb-inverse); }",
    "button[type=\"submit\"]:hover { background: var(--sb-primary-hover); border-color: var(--sb-primary-hover); }",
    "a { color: var(--sb-link); }",
    "a:hover { text-decoration: underline; }",
    ":focus-visible { outline: 3px solid var(--sb-focus-ring); outline-offset: 2px; }",
    ".table { width: 100%; border-collapse: collapse; }",
    ".table th { text-align: left; color: var(--sb-muted); font-weight: 600; padding: 8px; border-bottom: 1px solid var(--sb-border); }",
    ".table td { padding: 8px; border-bottom: 1px solid var(--sb-border); }",
    ".table tbody tr:hover { background: var(--sb-elevated); }",
    ".nav-item { width: 100%; text-align: left; }",
    ".nav-item.active { border-color: var(--sb-primary); }",
    ".actions { display: flex; gap: 8px; flex-wrap: wrap; }",
    ".modal { position: fixed; inset: 0; display: flex; align-items: center; justify-content: center; padding: 16px; }",
    ".modal::before { content: \"\"; position: absolute; inset: 0; background: var(--sb-bg); opacity: 0.85; }",
    ".modal-content { position: relative; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 16px; width: min(720px, 100%); max-height: 85vh; overflow: auto; }",
    ".toast { position: fixed; top: 12px; left: 50%; transform: translateX(-50%); background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 999px; padding: 8px 12px; color: var(--sb-text); box-shadow: 0 6px 24px rgba(0, 0, 0, 0.15); display: flex; gap: 8px; align-items: center; max-width: calc(100vw - 24px); z-index: 50; }",
    ".toast span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 60vw; }",
    ".toast-dismiss { padding: 2px 8px; line-height: 1; }",
    ".icon-row { display: flex; gap: 8px; align-items: center; }",
    ".icon-preview { width: 32px; height: 32px; border: 1px solid var(--sb-border); border-radius: 10px; display: flex; align-items: center; justify-content: center; background: var(--sb-elevated); }",
    ".icon-picker { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 10px; }",
    ".icon-picker button { width: 44px; height: 44px; padding: 0; border-radius: 12px; display: inline-flex; align-items: center; justify-content: center; background: var(--sb-elevated); }",
    ".icon-picker button.active { border-color: var(--sb-primary); }",
    ".icon-picker img { width: 24px; height: 24px; }",
    ".task-card { background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; overflow: hidden; position: relative; }",
    ".task-card:hover, .task-card:focus-within { z-index: 10; overflow: visible; box-shadow: 0 10px 30px rgba(0,0,0,0.18); }",
    ".task-card-top { position: absolute; top: 8px; left: 8px; right: 8px; display: flex; justify-content: space-between; gap: 6px; align-items: center; z-index: 2; }",
    ".task-card-type-icon { display: none; }",
    ".task-card-actions { display: flex; gap: 6px; align-items: center; flex-shrink: 0; }",
    ".task-card-body { height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 6px; padding: 10px 10px 10px 10px; padding-top: 40px; box-sizing: border-box; }
.task-card-center { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px; }
.task-card-center-icon { width: 28px; height: 28px; display: inline-flex; align-items: center; justify-content: center; opacity: 0.9; }",
    ".task-card-title { width: 100%; font-weight: 700; font-size: 13px; line-height: 1.15; text-align: center; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }",
    ".task-card.highlight { border: 2px solid var(--sb-primary); }",
    ".task-card .secondary-action { display: inline-flex; opacity: 0.65; }",
    ".task-card:hover .secondary-action, .task-card:focus-within .secondary-action { opacity: 1; }",
    ".task-card-preview { position: absolute; top: 0; left: calc(100% + 8px); width: 280px; max-width: min(360px, calc(100vw - 24px)); background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 10px 12px; box-shadow: 0 10px 30px rgba(0,0,0,0.18); opacity: 0; transform: scale(0.98); transition: opacity 120ms ease, transform 120ms ease; transition-delay: 200ms; pointer-events: auto; z-index: 20; }
.task-card.preview-left .task-card-preview { left: auto; right: calc(100% + 8px); }",
    ".task-preview-grid { display: grid; grid-template-columns: auto 1fr; column-gap: 10px; row-gap: 6px; align-items: baseline; }",
    ".task-preview-label { color: var(--sb-muted); font-size: 12px; }",
    ".task-preview-value { font-size: 12px; text-align: right; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".task-preview-badge { display: inline-flex; align-items: center; padding: 2px 8px; border-radius: 999px; border: 1px solid var(--sb-border); background: color-mix(in oklab, var(--sb-elevated) 70%, transparent); font-weight: 600; }",
    ".task-preview-badge-available { border-color: color-mix(in oklab, var(--sb-primary) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-primary) 12%, var(--sb-elevated)); }",
    ".task-preview-badge-claimed { border-color: color-mix(in oklab, var(--sb-info) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-info) 12%, var(--sb-elevated)); }",
    ".task-preview-badge-ongoing { border-color: color-mix(in oklab, var(--sb-warning) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-warning) 14%, var(--sb-elevated)); }",
    ".task-preview-badge-completed { border-color: color-mix(in oklab, var(--sb-success) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-success) 12%, var(--sb-elevated)); }",
    ".task-card-preview::before { content: \"\"; position: absolute; left: -8px; top: 50%; transform: translateY(-50%); border-width: 8px 8px 8px 0; border-style: solid; border-color: transparent var(--sb-elevated) transparent transparent; }",
    ".task-card-preview::after { content: \"\"; position: absolute; left: -9px; top: 50%; transform: translateY(-50%); border-width: 9px 9px 9px 0; border-style: solid; border-color: transparent var(--sb-border) transparent transparent; }",
    ".task-card.preview-left .task-card-preview::before { left: auto; right: -8px; border-width: 8px 0 8px 8px; border-color: transparent transparent transparent var(--sb-elevated); }",
    ".task-card.preview-left .task-card-preview::after { left: auto; right: -9px; border-width: 9px 0 9px 9px; border-color: transparent transparent transparent var(--sb-border); }",
    ".task-card:hover .task-card-preview { opacity: 1; transform: scale(1); transition-delay: 350ms; }",
    ".task-card:focus-within .task-card-preview { opacity: 1; transform: scale(1); transition-delay: 0ms; }",
    ".drag-handle { cursor: grab; user-select: none; padding: 0; border: 1px solid var(--sb-border); border-radius: 8px; background: transparent; color: var(--sb-muted); display: inline-flex; align-items: center; justify-content: center; min-width: 28px; min-height: 28px; line-height: 0; }",
    ".drag-handle:hover { border-color: var(--sb-primary); }
.drag-handle:active { cursor: grabbing; }",
    ".task-list { display: flex; flex-direction: column; gap: 8px; }",
    ".task-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; padding: 10px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); }",
    ".task-row-title { font-weight: 700; }",
    ".task-row-meta { color: var(--sb-muted); font-size: 0.9em; }",
    ".task-row-actions { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; justify-content: flex-end; }",
    ".skills-list { display: flex; flex-direction: column; gap: 6px; }",
    ".skill-row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 10px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); }",
    ".skill-name { font-weight: 600; }",
    ".now-working { display: flex; align-items: center; justify-content: space-between; gap: 12px; flex-wrap: wrap; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 10px 12px; }",
    ".now-working-title { font-weight: 700; }",
    ".now-working-timer { font-variant-numeric: tabular-nums; color: var(--sb-muted); }",
    ".now-working-actions { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }",
    ".now-working-empty { color: var(--sb-muted); }",
    ".now-working-error { color: var(--sb-danger); }",
    "@media (max-width: 640px) { .body { flex-direction: column; } .nav { width: 100%; } }",
  ]
  |> string.join("\n")
}
