//// Auto-split CSS chunk: base

/// Provides base CSS chunk.
pub fn css() -> List(String) {
  [
    ":root { color-scheme: light dark; }",
    "/* Breakpoints: sm 640px, md 768px, lg 1024px */",
    "* { box-sizing: border-box; }",
    "body { margin: 0; font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; background: var(--sb-bg); color: var(--sb-text); }",
    ".app { min-height: 100vh; background: var(--sb-bg); color: var(--sb-text); padding: 16px; }",
    ".page { max-width: 480px; margin: 0 auto; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 16px; }",
    ".admin, .member { display: flex; flex-direction: column; gap: 12px; }",
    ".body { display: flex; gap: 12px; align-items: flex-start; }",
    ".nav { width: 220px; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; display: flex; flex-direction: column; gap: 8px; }",
    ".content { flex: 1; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; min-width: 0; }",
    ".content.pool-main { overflow: hidden; min-height: 520px; }",
    ".pool-layout { display: flex; gap: 12px; align-items: flex-start; width: 100%; }",
    ".pool-main { flex: 1 1 auto; min-width: 0; position: relative; overflow: hidden; }",
    ".pool-right { width: 360px; flex-shrink: 0; position: relative; z-index: 2; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; display: flex; flex-direction: column; gap: 10px; align-self: stretch; }
.pool-my-tasks-dropzone { border: 1px dashed transparent; border-radius: 12px; padding: 8px; transition: border-color 120ms ease, background 120ms ease; min-height: 120px; }
.pool-my-tasks-dropzone.drag-active { border-color: var(--sb-border); background: color-mix(in oklab, var(--sb-elevated) 70%, transparent); }
.pool-my-tasks-dropzone.drop-over { border-color: var(--sb-primary); background: color-mix(in oklab, var(--sb-primary) 12%, var(--sb-elevated)); }
.dropzone-hint { font-size: 12px; color: var(--sb-muted); margin-bottom: 6px; }",
    "@media (max-width: 1024px) { .pool-right { width: 320px; } }
@media (max-width: 1024px) { .pool-layout { flex-direction: column; } .pool-right { width: 100%; } }",
    // Pool unified toolbar (Story 4.8 - simplified)
    ".pool-toolbar { display: flex; align-items: center; gap: 12px; padding: 8px 0; margin-bottom: 12px; }",
    ".pool-toolbar-minimal { justify-content: flex-end; }",
    ".pool-toolbar-spacer { flex: 1; }",
    ".pool-toolbar-left { display: flex; gap: 4px; }",
    ".pool-toolbar-center { flex: 1; display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }",
    ".pool-toolbar-right { display: flex; gap: 4px; }",
    ".btn-filter-toggle { position: relative; }",
    ".btn-filter-toggle.has-active { border-color: var(--sb-accent); }",
    ".filter-count-badge { display: inline-flex; align-items: center; justify-content: center; min-width: 16px; height: 16px; padding: 0 4px; margin-left: 4px; background: var(--sb-accent); color: var(--sb-bg); border-radius: 8px; font-size: 10px; font-weight: 600; }",
    ".pool-inline-filters { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }",
    ".pool-inline-filters .filter-select { height: 28px; padding: 4px 8px; font-size: 12px; min-width: 100px; max-width: 140px; }",
    ".pool-inline-filters .filter-search { height: 28px; padding: 4px 8px; font-size: 12px; width: 120px; }",
    ".pool-inline-filters .btn-xs { height: 28px; padding: 4px 8px; }",
    ".pool-inline-filters .btn-clear { padding: 4px 6px; font-size: 11px; color: var(--sb-muted); }",
    ".pool-inline-filters .btn-clear:hover { color: var(--sb-danger); border-color: var(--sb-danger); }",
    "@media (max-width: 768px) { .pool-toolbar { flex-wrap: wrap; } .pool-toolbar-center { order: 3; width: 100%; } }",
    ".topbar { display: flex; align-items: center; gap: 12px; justify-content: space-between; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px; }",
    ".topbar-title { font-weight: 700; }",
    ".topbar-actions { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }",
    ".topbar-group { display: inline-flex; align-items: center; gap: 8px; }",
    // H01-H03: Settings group in topbar
    ".topbar-settings-group { display: inline-flex; align-items: center; gap: 4px; padding: 4px 8px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 10px; }",
    ".theme-switch { display: inline-flex; align-items: center; gap: 8px; }",
    ".user { color: var(--sb-muted); }",
    ".section { display: flex; flex-direction: column; gap: 10px; }",
    ".field { display: flex; flex-direction: column; gap: 4px; margin: 8px 0; }",
    ".required-indicator { color: var(--sb-danger); margin-left: 4px; font-weight: 600; }",
    ".filters-row { display: flex; gap: 10px; align-items: stretch; flex-wrap: nowrap; overflow-x: auto; padding-bottom: 2px; }",
    ".filters-row .field { margin: 0; min-width: 140px; position: relative; }",
    ".filters-row .field.filter-q { min-width: 180px; }",
    ".filters-row .filter-icon { display: none; font-size: 12px; color: var(--sb-muted); }",
    ".filters-row select, .filters-row input, .filters-row button { height: 36px; }",
    ".filters-row button { padding: 8px 12px; }",
    ".filters-row .filter-tooltip { display: none; position: absolute; left: 0; top: -26px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 999px; padding: 2px 8px; font-size: 12px; color: var(--sb-text); white-space: nowrap; }",
    "@media (max-width: 1024px) { .filters-row { gap: 8px; } .filters-row .filter-label { display: none; } .filters-row .filter-icon { display: inline; } .filters-row .field { min-width: 56px; } .filters-row select, .filters-row input { padding: 6px; } .filters-row .field:hover .filter-tooltip, .filters-row .field:focus-within .filter-tooltip { display: inline-flex; } }",
    ".filter-actions { display: flex; align-items: center; gap: 8px; margin-left: auto; }",
    ".filter-badge { display: inline-flex; align-items: center; justify-content: center; min-width: 20px; height: 20px; padding: 0 6px; background: var(--sb-accent); color: var(--sb-bg); border-radius: 10px; font-size: 12px; font-weight: 600; }",
    ".btn-clear-filters { font-size: 12px; padding: 4px 10px !important; height: 28px !important; }",
    ".hint { color: var(--sb-muted); font-size: 0.9em; }",
    ".empty { color: var(--sb-muted); }",
    ".loading { color: var(--sb-info); }",
    ".spinner { border: 2px solid var(--sb-border); border-top-color: var(--sb-primary); border-radius: 50%; animation: spin 0.6s linear infinite; }",
    ".spinner-sm { width: 16px; height: 16px; }",
    ".spinner-md { width: 24px; height: 24px; }",
    ".spinner-lg { width: 32px; height: 32px; }",
    "@keyframes spin { to { transform: rotate(360deg); } }",
    ".error { color: var(--sb-danger); }",
    ".field-error { color: var(--sb-danger); font-size: 0.875rem; margin-top: 0.25rem; display: flex; align-items: center; gap: 0.25rem; }",
    "input, select, textarea { padding: 8px; border-radius: 10px; border: 1px solid var(--sb-border); background: var(--sb-elevated); color: var(--sb-text); font-family: inherit; }",
    "button { padding: 8px 12px; border-radius: 10px; border: 1px solid var(--sb-border); background: var(--sb-elevated); color: var(--sb-text); cursor: pointer; }",
    ".btn-xs { padding: 4px 8px; font-size: 12px; border-radius: 8px; }",
    ".btn-active { border-color: var(--sb-primary); }",
    ".btn-icon { display: inline-flex; align-items: center; justify-content: center; min-width: 28px; min-height: 28px; line-height: 1; position: relative; }",
    ".btn-icon[data-tooltip]::after { content: attr(data-tooltip); display: none; position: absolute; right: 0; top: -28px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 999px; padding: 2px 8px; font-size: 12px; color: var(--sb-text); white-space: nowrap; }",
    ".btn-icon[data-tooltip]:hover::after, .btn-icon[data-tooltip]:focus-visible::after { display: inline-flex; }",
    "button:hover { border-color: var(--sb-primary); }",
    "button:disabled { opacity: 0.6; cursor: not-allowed; }",
    "button[type=\"submit\"] { background: var(--sb-primary); border-color: var(--sb-primary); color: var(--sb-inverse); }",
    "button[type=\"submit\"]:hover { background: var(--sb-primary-hover); border-color: var(--sb-primary-hover); }",
    "a { color: var(--sb-link); }",
    "a:hover { text-decoration: underline; }",
    ":focus-visible { outline: 3px solid var(--sb-focus-ring); outline-offset: 2px; }",
  ]
}
