//// Auto-split CSS chunk: layout

/// Provides layout CSS chunk.
pub fn css() -> List(String) {
  [
    ".three-panel-layout { display: grid; grid-template-columns: minmax(248px, 264px) minmax(0, 1fr) minmax(280px, 320px); gap: var(--sb-space-lg); min-height: calc(100vh - 48px); align-items: start; }",
    ".panel-left { background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: var(--sb-radius-xl); padding: var(--sb-space-lg); display: flex; flex-direction: column; gap: var(--sb-space-md); position: sticky; top: var(--sb-space-lg); max-height: calc(100vh - 48px); overflow-y: auto; scrollbar-gutter: stable; }",
    ".panel-center { background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: var(--sb-radius-xl); padding: var(--sb-space-lg); min-width: 0; width: 100%; animation: view-fade-in 0.15s ease; }",
    "@keyframes view-fade-in { from { opacity: 0.6; } to { opacity: 1; } }",
    ".panel-right { background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: var(--sb-radius-xl); padding: var(--sb-space-lg); display: flex; flex-direction: column; gap: var(--sb-space-lg); position: sticky; top: var(--sb-space-lg); max-height: calc(100vh - 48px); overflow-y: auto; }",
    "@media (max-width: 1180px) { .three-panel-layout { grid-template-columns: minmax(232px, 248px) minmax(0, 1fr); } .panel-right { display: none; } }",
    "@media (max-width: 768px) { .three-panel-layout { grid-template-columns: 1fr; min-height: 0; } .panel-left { display: none; } .panel-right { display: none; } .panel-center { padding: var(--sb-space-md); } }",
    ".left-panel-content { display: flex; flex-direction: column; gap: var(--sb-gap-section); min-width: 0; }",
    ".project-selector-section { margin-bottom: var(--sb-gap-related); }",
    ".project-selector-dropdown { width: 100%; padding: 10px 12px; border-radius: var(--sb-radius-lg); border: 1px solid var(--sb-border); background: var(--sb-elevated); font-weight: var(--sb-weight-semibold); font-size: var(--sb-font-md); line-height: var(--sb-line-tight); color: var(--sb-text-strong); }",
    ".panel-section { display: flex; flex-direction: column; gap: var(--sb-gap-related); min-width: 0; }",
    ".section-items { display: flex; flex-direction: column; gap: 2px; overflow: hidden; max-height: 500px; opacity: 1; transition: opacity var(--sb-transition-normal); min-width: 0; }",
    ".section-items-collapsed { max-height: 0; opacity: 0; margin: 0; }",
    ".section-title { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-bold); text-transform: uppercase; letter-spacing: var(--sb-letter-label); line-height: var(--sb-line-tight); color: var(--sb-muted-strong); margin: 0 0 var(--sb-space-sm) 0; }",
    ".btn-action { display: flex; align-items: center; gap: var(--sb-space-md); width: 100%; padding: var(--sb-space-md) var(--sb-space-lg); text-align: left; background: transparent; border: 1px solid transparent; border-radius: var(--sb-radius-md); cursor: pointer; color: var(--sb-text); transition: background var(--sb-transition-normal); }",
    ".btn-action:hover { background: var(--sb-elevated); }",
    ".btn-action:disabled { opacity: 0.5; cursor: not-allowed; }",
    ".btn-icon-prefix { font-weight: 700; color: var(--sb-primary); }",
    ".btn-action-primary { background: var(--sb-primary); border: 1px solid var(--sb-primary); color: var(--sb-inverse); font-weight: var(--sb-weight-semibold); border-radius: var(--sb-radius-lg); }",
    ".btn-action-primary:hover { background: var(--sb-primary-hover); border-color: var(--sb-primary-hover); }",
    ".btn-action-primary .btn-icon-prefix { color: inherit; }",
    ".btn-action-shortcut { background: color-mix(in oklab, var(--sb-primary) 7%, var(--sb-surface)); border-color: color-mix(in oklab, var(--sb-primary) 22%, var(--sb-border)); color: var(--sb-text-strong); font-weight: var(--sb-weight-semibold); border-radius: var(--sb-radius-lg); }",
    ".btn-action-shortcut:hover { background: color-mix(in oklab, var(--sb-primary) 12%, var(--sb-surface)); border-color: color-mix(in oklab, var(--sb-primary) 40%, var(--sb-border)); }",
    ".btn-action-shortcut:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; }",
    ".btn-action-shortcut .btn-icon-prefix { color: var(--sb-primary); }",
    ".btn-primary .btn-icon-prefix { color: inherit; }",
    ".nav-links { display: flex; flex-direction: column; gap: 2px; margin-top: var(--sb-gap-group); padding-top: var(--sb-gap-group); border-top: 1px solid color-mix(in oklab, var(--sb-border) 72%, transparent); }",
    ".nav-link { display: flex; align-items: center; gap: var(--sb-gap-related); width: 100%; min-width: 0; padding: var(--sb-gap-related) var(--sb-gap-group); text-align: left; background: transparent; border: 1px solid transparent; border-radius: 8px; cursor: pointer; color: var(--sb-text); }",
    ".nav-link:hover { background: var(--sb-elevated); }",
    ".nav-link:disabled { opacity: 0.5; cursor: not-allowed; }",
    ".nav-link.active { background: var(--sb-primary-subtle-bg); border-color: var(--sb-primary-subtle-border); color: var(--sb-text-strong); box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--sb-primary) 18%, transparent); }",
    ".nav-icon { font-size: 14px; }",
    ".nav-label { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".nav-link .nav-icon, .nav-link .badge, .nav-link .active-indicator { flex-shrink: 0; }",
    ".active-indicator { color: var(--sb-primary); font-size: 8px; }",
    ".right-panel-content { display: flex; flex-direction: column; gap: 16px; height: 100%; min-width: 0; }",
    ".active-task-section, .my-tasks-section, .my-cards-section { display: flex; flex-direction: column; gap: 8px; min-width: 0; }",
    ".active-task-card { background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 10px; padding: 12px; position: relative; }",
    ".active-task-card.card-border-gray, .active-task-card.card-border-red, .active-task-card.card-border-orange, .active-task-card.card-border-yellow, .active-task-card.card-border-green, .active-task-card.card-border-blue, .active-task-card.card-border-purple, .active-task-card.card-border-pink { border-color: color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 36%, var(--sb-border)); background: color-mix(in oklab, var(--sb-card-accent, var(--sb-elevated)) 5%, var(--sb-elevated)); }",
    ".active-tasks-list { display: flex; flex-direction: column; gap: 8px; max-height: 200px; overflow-y: auto; min-width: 0; }",
    ".active-tasks-list .active-task-card { padding: 10px; }",
    ".active-tasks-list .task-timer { font-size: var(--sb-font-xl); margin: 4px 0; }",
    ".task-timer { font-family: var(--sb-font-mono); font-size: var(--sb-font-3xl); font-weight: var(--sb-weight-bold); font-variant-numeric: tabular-nums; line-height: var(--sb-line-tight); text-align: center; margin: 8px 0; }",
    ".task-actions { display: flex; gap: 8px; justify-content: center; }",
    ".task-list { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".task-item { display: flex; align-items: center; justify-content: space-between; padding: 8px 10px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); gap: var(--sb-space-md); min-width: 0; animation: task-item-in 0.25s ease; }",
    "@keyframes task-item-in { from { opacity: 0; transform: translateY(-4px); } to { opacity: 1; transform: translateY(0); } }",
    ".task-item.card-border-gray, .task-item.card-border-red, .task-item.card-border-orange, .task-item.card-border-yellow, .task-item.card-border-green, .task-item.card-border-blue, .task-item.card-border-purple, .task-item.card-border-pink { border-color: color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 34%, var(--sb-border)); background: color-mix(in oklab, var(--sb-card-accent, var(--sb-elevated)) 4%, var(--sb-elevated)); }",
    ".task-card-identity-swatch { width: 4px; min-height: 28px; align-self: stretch; flex: 0 0 4px; border-radius: var(--sb-radius-pill); background: var(--sb-card-accent, transparent); box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 70%, var(--sb-border)); }",
    ".task-title-row { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; }",
    ".task-title-button { display: inline-flex; align-items: center; gap: 6px; min-width: 0; flex: 1; background: transparent; border: none; padding: 0; text-align: left; color: inherit; cursor: pointer; }",
    ".task-title-button:hover .task-title { color: var(--sb-primary); }",
    ".task-type-icon { flex-shrink: 0; display: flex; align-items: center; justify-content: center; }",
    ".task-item .task-title { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: var(--sb-font-base); line-height: var(--sb-line-title); }",
    ".task-item .task-actions { display: flex; gap: 4px; flex-shrink: 0; }",
    ".task-item-action-slot { display: flex; align-items: center; justify-content: flex-end; min-width: 28px; min-height: 28px; flex-shrink: 0; }",
    ".task-item-action-slot-placeholder { display: block; width: 28px; height: 28px; visibility: hidden; }",
    ".task-item-action-slot-compact { min-width: 20px; min-height: 20px; }",
    ".task-item-action-slot-compact .task-item-action-slot-placeholder { width: 20px; height: 20px; }",
    ".scope-toggle { display: inline-flex; border: 1px solid var(--sb-border); border-radius: 8px; overflow: hidden; background: var(--sb-surface); }",
    ".scope-toggle-btn { border: none; background: transparent; color: var(--sb-muted); padding: 6px 10px; font-size: var(--sb-font-sm); cursor: pointer; }",
    ".scope-toggle-btn + .scope-toggle-btn { border-left: 1px solid var(--sb-border); }",
    ".scope-toggle-btn.is-active { background: var(--sb-primary); color: var(--sb-inverse); }",
    ".active-task-card .task-title-row { justify-content: center; }",
    ".active-task-card .task-title { text-align: center; font-weight: var(--sb-weight-medium); min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".my-cards-list { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".my-card-item { display: flex; flex-direction: column; gap: 4px; width: 100%; min-width: 0; padding: 10px 12px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 8px; cursor: pointer; text-align: left; }",
    ".my-card-item.card-border-gray, .my-card-item.card-border-red, .my-card-item.card-border-orange, .my-card-item.card-border-yellow, .my-card-item.card-border-green, .my-card-item.card-border-blue, .my-card-item.card-border-purple, .my-card-item.card-border-pink { border-color: color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 34%, var(--sb-border)); background: color-mix(in oklab, var(--sb-card-accent, var(--sb-elevated)) 4%, var(--sb-elevated)); }",
    ".my-card-item:hover { border-color: var(--sb-primary); background: var(--sb-surface); }",
    ".my-card-item .card-title { font-weight: var(--sb-weight-medium); font-size: var(--sb-font-md); line-height: var(--sb-line-title); min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".card-progress-row { display: flex; align-items: center; gap: 8px; }",
    ".progress-bar-mini { flex: 1; height: 4px; background: var(--sb-border); border-radius: 2px; overflow: hidden; }",
    ".progress-bar-mini .progress-bar-fill { height: 100%; background: var(--sb-primary); border-radius: 2px; }",
    ".card-progress { font-size: var(--sb-font-sm); color: var(--sb-muted); font-variant-numeric: tabular-nums; }",
    ".right-panel-activity { display: flex; flex-direction: column; gap: 16px; flex: 1; }",
    ".right-panel-footer { display: flex; flex-direction: column; gap: 12px; margin-top: auto; padding-top: 16px; border-top: 1px solid var(--sb-border); }",
    ".section-title-with-icon { display: flex; align-items: center; gap: 8px; }",
    ".section-title-with-icon .nav-icon { color: var(--sb-muted); }",
    ".preferences-popup-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.3); display: flex; align-items: center; justify-content: center; z-index: 1000; padding: 16px; }",
    ".preferences-popup { background: var(--sb-surface); border-radius: 12px; padding: 16px; width: min(320px, 100%); max-height: min(420px, calc(100vh - 32px)); overflow: auto; box-shadow: 0 8px 32px rgba(0,0,0,0.2); }",
    ".popup-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 16px; }",
    ".popup-title { display: flex; align-items: center; gap: 8px; min-width: 0; margin: 0; font-size: var(--sb-font-lg); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); }",
    ".popup-title .nav-icon { color: var(--sb-muted); }",
    ".preferences-popup-content { display: flex; flex-direction: column; gap: 12px; }",
    ".preference-item { display: flex; align-items: center; gap: 8px; cursor: pointer; min-width: 0; }",
    ".preference-icon { display: flex; align-items: center; color: var(--sb-muted); }",
    ".preference-select { flex: 1; min-width: 0; padding: 8px 12px; border-radius: 8px; border: 1px solid var(--sb-border); background: var(--sb-elevated); font-size: var(--sb-font-md); cursor: pointer; }",
    ".preference-select:hover { border-color: var(--sb-primary); }",
    ".section-empty-hint { color: var(--sb-link); font-size: var(--sb-font-sm); font-style: italic; padding: 10px 12px; margin: 4px 0; border: 1px dashed color-mix(in oklab, var(--sb-link) 40%, var(--sb-border)); border-radius: var(--sb-radius-md); background: color-mix(in oklab, var(--sb-link) 6%, var(--sb-surface)); text-align: center; }",
    ".pool-my-tasks-dropzone .section-empty-hint { padding-left: 16px; }",
    ".profile-section { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 12px 0; }",
    ".profile-section .user-info { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; }",
    ".profile-section .user-info .nav-icon { color: var(--sb-muted); flex-shrink: 0; }",
    ".profile-section .user-email { font-size: var(--sb-font-base); color: var(--sb-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".profile-actions { display: flex; align-items: center; gap: 4px; flex-shrink: 0; }",
    ".btn-icon-only { display: flex; align-items: center; justify-content: center; width: 32px; height: 32px; padding: 0; background: transparent; border: 1px solid transparent; border-radius: 8px; cursor: pointer; color: var(--sb-muted); transition: all 0.15s ease; }",
    ".btn-icon-only:hover { background: var(--sb-elevated); color: var(--sb-text); border-color: var(--sb-border); }",
    ".btn-icon-only.btn-logout:hover { color: var(--sb-error); border-color: var(--sb-error); }",
    ".view-mode-toggle { display: inline-flex; gap: 4px; padding: 4px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; }",
    ".view-mode-btn { display: flex; align-items: center; gap: 6px; padding: 8px 12px; background: transparent; border: none; border-radius: 8px; cursor: pointer; color: var(--sb-text); transition: all 0.15s ease; }",
    ".view-mode-btn:hover { background: var(--sb-surface); }",
    ".view-mode-btn.active { background: var(--sb-primary); color: var(--sb-inverse); }",
    ".view-mode-icon { font-size: 16px; }",
    ".view-mode-label { font-size: var(--sb-font-md); font-weight: var(--sb-weight-medium); }",
    "@media (max-width: 768px) { .view-mode-label { display: none; } }",
    ".center-panel-content { display: flex; flex-direction: column; gap: var(--sb-gap-section); height: 100%; }",
    ".center-toolbar { display: flex; align-items: center; gap: var(--sb-gap-group); flex-wrap: wrap; }",
    ".center-filters { display: flex; gap: var(--sb-gap-related) var(--sb-gap-group); align-items: center; flex-wrap: wrap; margin-left: auto; }",
    ".center-filters-work { margin-left: 0; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: var(--sb-gap-related) var(--sb-gap-group); width: 100%; }",
    ".center-filters-work .filter-field label { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); color: var(--sb-text); }",
    ".center-filters-work .filter-field select, .center-filters-work .filter-field input { background: var(--sb-surface); }",
    ".filter-field { display: flex; flex-direction: column; gap: var(--sb-gap-tight); }",
    ".filter-field label { font-size: var(--sb-font-xs); color: var(--sb-muted-strong); }",
    ".filter-field select, .filter-field input { padding: 6px 10px; border-radius: 8px; border: 1px solid var(--sb-border); background: var(--sb-elevated); min-width: 120px; }",
    ".filter-search input { min-width: 160px; }",
    ".center-filters-people { margin-left: 0; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: var(--sb-gap-related) var(--sb-gap-group); width: 100%; }",
    ".center-filters-people .filter-field { width: 100%; max-width: 420px; }",
    ".center-filters-people .filter-field label { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); color: var(--sb-text); }",
    ".center-filters-people .filter-search input { width: 100%; min-width: 220px; background: var(--sb-surface); }",
    ".center-content { flex: 1; overflow: auto; }",
    ".people-view { display: flex; flex-direction: column; gap: 10px; }",
    ".people-list { display: flex; flex-direction: column; gap: 10px; }",
    ".people-list ul, .people-items { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 10px; }",
    ".people-row { border: 1px solid var(--sb-border); border-radius: 10px; background: var(--sb-surface); padding: 10px 12px; transition: border-color 0.15s ease, box-shadow 0.15s ease; }",
    ".people-row:hover { border-color: var(--sb-primary); box-shadow: 0 1px 0 rgba(0,0,0,0.03); }",
    ".people-row-header { display: grid; grid-template-columns: minmax(180px, 0.9fr) minmax(0, 1.4fr); align-items: center; gap: 10px; }",
    ".people-row-main { display: flex; align-items: center; gap: 8px; min-width: 0; }",
    ".people-row-toggle { display: inline-flex; align-items: center; gap: 8px; min-width: 0; background: transparent; border: none; text-align: left; cursor: pointer; padding: 0; }",
    ".people-row-toggle:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; border-radius: 6px; }",
    ".people-row-caret { color: var(--sb-muted); width: 14px; text-align: center; }",
    ".people-row-name { font-weight: var(--sb-weight-semibold); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".people-status-chip { font-size: var(--sb-font-sm); flex-shrink: 0; }",
    ".people-row-balance { display: flex; align-items: center; justify-content: flex-end; flex-wrap: wrap; gap: 5px; min-width: 0; }",
    ".people-metric-chip, .people-load-chip { font-size: var(--sb-font-xs); font-variant-numeric: tabular-nums; }",
    ".people-card-set { display: inline-flex; align-items: center; flex-wrap: wrap; gap: 5px; min-width: 0; }",
    ".people-card-chip { display: inline-flex; align-items: center; max-width: 140px; min-height: 22px; padding: 2px 7px; border-radius: var(--sb-radius-pill); border: 1px solid var(--sb-border); background: color-mix(in oklab, var(--sb-elevated) 72%, transparent); color: var(--sb-muted-strong); font-size: var(--sb-font-xs); line-height: var(--sb-line-tight); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".people-card-empty { color: var(--sb-muted); font-size: var(--sb-font-xs); line-height: var(--sb-line-tight); }",
    ".people-row-details { margin-top: 10px; padding-top: 10px; border-top: 1px dashed var(--sb-border); display: grid; grid-template-columns: 1fr; gap: 8px; }",
    ".people-subsection { border: 1px solid var(--sb-border); border-radius: 8px; background: var(--sb-elevated); padding: 8px 10px; display: flex; flex-direction: column; gap: 7px; }",
    ".people-subsection-title { margin: 0; font-size: var(--sb-font-xs); color: var(--sb-muted-strong); text-transform: uppercase; letter-spacing: var(--sb-letter-label); line-height: var(--sb-line-tight); }",
    ".people-task-item { margin: 0; font-size: var(--sb-font-base); line-height: var(--sb-line-title); color: var(--sb-text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".people-task-link { appearance: none; background: transparent; border: none; color: var(--sb-primary); cursor: pointer; font: inherit; margin: 0; padding: 0; text-align: left; text-decoration: none; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".people-task-link:hover { text-decoration: underline; }",
    ".people-task-link:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; border-radius: 4px; }",
    ".people-task-empty { margin: 0; font-size: var(--sb-font-base); color: var(--sb-muted); }",
    ".people-claimed-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 4px; }",
    ".people-claimed-list .task-item { padding: 7px 8px; background: color-mix(in oklab, var(--sb-elevated) 68%, var(--sb-surface)); }",
    ".people-claimed-list .task-item-content { min-width: 0; overflow: hidden; }",
    ".people-claimed-list .task-card-identity-swatch { min-height: 24px; }",
    ".people-task-meta { display: inline-flex; align-items: center; gap: 6px; min-width: 0; color: var(--sb-muted); }",
    ".people-state { color: var(--sb-muted); padding: 16px 4px; }",
    ".people-error { color: var(--sb-error); }",
    "@media (max-width: 768px) { .center-filters-people { padding: var(--sb-gap-related) var(--sb-gap-group); } }",
    "@media (max-width: 768px) { .center-panel-content { gap: var(--sb-gap-group); } .center-filters-work { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); align-items: stretch; gap: var(--sb-gap-related) var(--sb-gap-group); padding: var(--sb-gap-related); border-radius: 10px; background: color-mix(in oklab, var(--sb-elevated) 62%, transparent); } .center-filters-work .filter-field { display: grid; grid-template-columns: auto minmax(0, 1fr); align-items: center; column-gap: var(--sb-gap-related); min-width: 0; width: 100%; } .center-filters-work .filter-field label { font-size: var(--sb-font-xs); line-height: var(--sb-line-tight); white-space: nowrap; } .center-filters-work .filter-field-scope, .center-filters-work .filter-search { grid-column: 1 / -1; } .center-filters-work .filter-field-scope { grid-template-columns: minmax(88px, auto) minmax(0, 1fr); } .center-filters-work .filter-search { grid-template-columns: minmax(48px, auto) minmax(0, 1fr); } .center-filters-work .filter-field select, .center-filters-work .filter-field input { width: 100%; min-width: 0; min-height: 44px; } .center-filters-work .scope-toggle { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); width: 100%; } .center-filters-work .scope-toggle-btn { min-height: 44px; padding-inline: var(--sb-gap-related); } }",
    "@media (max-width: 380px) { .center-filters-work { grid-template-columns: 1fr; } }",
    "@media (max-width: 768px) { .people-row-header { grid-template-columns: 1fr; align-items: start; } .people-row-balance { justify-content: flex-start; } }",
    ".hierarchies-view { display: flex; flex-direction: column; gap: 14px; }",
    ".hierarchies-shell { display: grid; grid-template-columns: minmax(280px, 340px) minmax(0, 1fr); gap: 14px; align-items: start; }",
    ".hierarchies-list-pane { display: flex; flex-direction: column; gap: 12px; position: sticky; top: 12px; }",
    ".hierarchies-list-section { background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px 14px; }",
    ".hierarchy-detail-pane { display: flex; flex-direction: column; min-width: 0; }",
    ".hierarchy-detail-main, .hierarchy-detail-empty { background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 14px; display: flex; flex-direction: column; gap: 14px; min-height: 320px; }",
    ".hierarchy-detail-empty { justify-content: center; }",
    ".hierarchy-detail-header { display: flex; flex-direction: column; gap: 10px; }",
    ".hierarchy-detail-header-main { display: flex; justify-content: space-between; align-items: flex-start; gap: 12px; }",
    ".hierarchy-detail-heading { display: flex; flex-direction: column; gap: 8px; min-width: 0; }",
    ".hierarchy-detail-actions { display: inline-flex; align-items: center; justify-content: flex-start; gap: 8px; flex-wrap: wrap; padding-top: 2px; }",
    ".hierarchy-detail-actions .btn-create-card { color: color-mix(in oklab, var(--sb-primary) 82%, var(--sb-text)); background: color-mix(in oklab, var(--sb-primary) 10%, transparent); border-color: color-mix(in oklab, var(--sb-primary) 26%, transparent); }",
    ".hierarchy-detail-actions .btn-create-card:hover { background: color-mix(in oklab, var(--sb-primary) 16%, transparent); border-color: color-mix(in oklab, var(--sb-primary) 42%, var(--sb-border)); }",
    ".hierarchy-detail-actions .btn-create-task { color: color-mix(in oklab, var(--sb-success) 72%, var(--sb-text)); background: color-mix(in oklab, var(--sb-success) 10%, transparent); border-color: color-mix(in oklab, var(--sb-success) 24%, transparent); }",
    ".hierarchy-detail-actions .btn-create-task:hover { background: color-mix(in oklab, var(--sb-success) 15%, transparent); border-color: color-mix(in oklab, var(--sb-success) 38%, var(--sb-border)); }",
    ".hierarchy-detail-title { margin: 0; font-size: var(--sb-font-2xl); font-weight: var(--sb-weight-bold); line-height: var(--sb-line-title); }",
    ".hierarchy-planning-summary { display: flex; flex-direction: column; gap: 8px; }",
    ".hierarchy-loose-tasks-panel { display: flex; flex-direction: column; gap: 10px; }",
    ".hierarchies-empty-actions { margin-top: 10px; }",
    ".hierarchies-filters { display: flex; flex-direction: column; gap: 10px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px 14px; }",
    ".hierarchies-search { width: 100%; min-height: 36px; border: 1px solid var(--sb-border); border-radius: 10px; padding: 0 12px; background: var(--sb-surface); color: var(--sb-text); }",
    ".hierarchies-filter-row { display: flex; flex-wrap: wrap; gap: 8px; }",
    ".hierarchies-filter-chip { display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px; border: 1px solid var(--sb-border); border-radius: 999px; background: var(--sb-surface); cursor: pointer; font-size: var(--sb-font-base); color: var(--sb-text); }",
    ".hierarchies-filter-chip:hover { border-color: var(--sb-primary); }",
    ".hierarchies-filter-checkbox { margin: 0; }",
    ".hierarchies-section { background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px 14px; }",
    ".hierarchies-section-title { margin: 0 0 10px 0; font-size: var(--sb-font-sm); color: var(--sb-muted-strong); text-transform: uppercase; letter-spacing: var(--sb-letter-label); line-height: var(--sb-line-tight); }",
    ".hierarchies-section-empty { margin: 0; color: var(--sb-muted); }",
    ".hierarchies-items { display: flex; flex-direction: column; gap: 10px; }",
    ".hierarchy-item { border: 1px solid var(--sb-border); border-radius: 10px; background: var(--sb-surface); padding: 12px 14px; display: flex; flex-direction: column; gap: 10px; transition: border-color 0.15s ease, box-shadow 0.15s ease; }",
    ".hierarchy-item:hover { border-color: var(--sb-primary); box-shadow: 0 1px 0 rgba(0,0,0,0.03); }",
    ".hierarchy-item-selected { border-color: var(--sb-primary); box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--sb-primary) 45%, var(--sb-border)); }",
    ".hierarchy-item-header { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap: 10px; }",
    ".hierarchy-row-header-main { display: inline-flex; align-items: center; gap: 8px; min-width: 0; }",
    ".hierarchy-activate-btn { background: color-mix(in oklab, var(--sb-success) 18%, var(--sb-surface)); border-color: color-mix(in oklab, var(--sb-success) 55%, var(--sb-border)); color: color-mix(in oklab, var(--sb-success) 85%, var(--sb-text)); font-weight: var(--sb-weight-semibold); }",
    ".hierarchy-activate-btn:hover { background: color-mix(in oklab, var(--sb-success) 24%, var(--sb-surface)); border-color: color-mix(in oklab, var(--sb-success) 70%, var(--sb-border)); }",
    ".hierarchy-row-toggle { display: inline-flex; align-items: center; justify-content: center; appearance: none; border: 1px solid transparent; background: transparent; border-radius: 8px; width: 28px; height: 28px; padding: 0; cursor: pointer; color: var(--sb-text); flex-shrink: 0; }",
    ".hierarchy-row-toggle:hover { background: var(--sb-elevated); border-color: var(--sb-border); }",
    ".hierarchy-row-toggle:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; }",
    ".hierarchy-row-title-link { appearance: none; border: 0; background: transparent; color: var(--sb-text); font-size: var(--sb-font-lg); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); min-width: 0; padding: 0; text-align: left; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; cursor: pointer; }",
    ".hierarchy-row-title-link:hover { color: var(--sb-primary); text-decoration: underline; text-underline-offset: 2px; }",
    ".hierarchy-row-title-link:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; border-radius: 4px; }",
    ".hierarchy-item-meta { display: inline-flex; align-items: center; gap: 10px; justify-self: end; flex-wrap: wrap; }",
    ".hierarchy-progress-percent { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); color: var(--sb-muted); min-width: 34px; text-align: right; font-variant-numeric: tabular-nums; }",
    ".hierarchy-progress-bar { width: 128px; height: 10px; border: 1px solid var(--sb-border); border-radius: 999px; background: var(--sb-elevated); overflow: hidden; }",
    ".hierarchy-progress-fill { height: 100%; background: var(--sb-primary); border-radius: 999px; }",
    ".hierarchy-details-link { white-space: nowrap; padding: 4px 8px; border-radius: 8px; }",
    ".hierarchy-item-description { margin: 0; color: var(--sb-muted); font-size: var(--sb-font-sm); line-height: var(--sb-line-body); max-width: var(--sb-measure-prose); }",
    ".hierarchy-item-stats { display: inline-flex; align-items: center; gap: 6px; flex-wrap: wrap; }",
    ".hierarchy-stat-pill { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-medium); color: var(--sb-muted); border: 1px solid color-mix(in oklab, var(--sb-border) 70%, transparent); border-radius: 999px; padding: 2px 8px; background: color-mix(in oklab, var(--sb-elevated) 75%, transparent); font-variant-numeric: tabular-nums; }",
    ".hierarchy-structure-strip { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; padding: 2px 0; }",
    ".hierarchy-structure-chip { display: inline-flex; align-items: center; min-height: 24px; border: 1px solid color-mix(in oklab, var(--sb-border) 82%, transparent); border-radius: 999px; background: color-mix(in oklab, var(--sb-elevated) 82%, transparent); color: var(--sb-muted-strong); padding: 2px 8px; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-medium); line-height: var(--sb-line-tight); font-variant-numeric: tabular-nums; }",
    ".hierarchy-structure-chip.progress, .hierarchy-structure-chip.cards, .hierarchy-structure-chip.tasks { color: var(--sb-text); }",
    ".hierarchy-structure-chip.loose, .hierarchy-structure-chip.empty, .hierarchy-structure-chip.no-progress { border-color: color-mix(in oklab, var(--sb-warning) 38%, var(--sb-border)); color: color-mix(in oklab, var(--sb-warning) 70%, var(--sb-text)); background: color-mix(in oklab, var(--sb-warning) 8%, var(--sb-elevated)); }",
    ".hierarchy-structure-chip.blocked { border-color: color-mix(in oklab, var(--sb-error) 34%, var(--sb-border)); color: var(--sb-error); background: color-mix(in oklab, var(--sb-error) 7%, var(--sb-elevated)); }",
    ".action-row { margin-top: 2px; display: flex; align-items: center; justify-content: space-between; gap: 10px; width: 100%; }",
    ".action-row-main { display: inline-flex; align-items: center; gap: 8px; flex-wrap: wrap; }",
    ".action-row-primary, .action-row-workflow { display: inline-flex; align-items: center; gap: 8px; flex-wrap: wrap; }",
    ".action-row-manage { display: inline-flex; align-items: center; gap: 8px; margin-left: auto; }",
    ".hierarchy-subsection { display: flex; flex-direction: column; gap: 8px; }",
    ".hierarchy-subsection-title { margin: 0; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); color: var(--sb-muted-strong); text-transform: uppercase; letter-spacing: var(--sb-letter-label); }",
    ".hierarchy-inline-section { border: 1px solid color-mix(in oklab, var(--sb-border) 75%, transparent); border-radius: 10px; background: color-mix(in oklab, var(--sb-elevated) 88%, transparent); padding: 10px 12px; }",
    ".hierarchy-summary-toggle { display: flex; align-items: center; justify-content: space-between; gap: 10px; width: 100%; border: none; background: transparent; padding: 0; text-align: left; cursor: pointer; }",
    ".hierarchy-summary-toggle::after { content: \"▾\"; font-size: 11px; color: var(--sb-muted); transform: rotate(0deg); transition: transform 0.15s ease; }",
    ".hierarchy-summary-toggle[aria-expanded=\"false\"]::after { transform: rotate(-90deg); }",
    ".hierarchy-summary-meta { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-medium); color: var(--sb-muted); }",
    ".hierarchy-diagnostic-list { display: flex; flex-direction: column; gap: 6px; }",
    ".hierarchy-diagnostic-item { margin: 0; font-size: var(--sb-font-sm); line-height: var(--sb-line-body); color: var(--sb-text); }",
    ".hierarchy-diagnostic-item.is-complete { color: var(--sb-success); font-weight: var(--sb-weight-medium); }",
    ".hierarchy-summary-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; }",
    ".hierarchy-summary-column { display: flex; flex-direction: column; gap: 8px; min-width: 0; }",
    ".hierarchy-summary-heading { margin: 0; font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); color: color-mix(in oklab, var(--sb-text) 88%, var(--sb-muted)); }",
    ".hierarchy-summary-list { display: flex; flex-direction: column; gap: 6px; }",
    ".hierarchy-summary-list .detail-row { grid-template-columns: 120px minmax(0, 1fr); gap: 10px; padding: 1px 0; }",
    ".hierarchy-summary-list .detail-label { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-medium); color: var(--sb-muted); }",
    ".hierarchy-summary-list .detail-value { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-medium); color: color-mix(in oklab, var(--sb-text) 90%, var(--sb-muted)); }",
    ".hierarchy-content-section { display: flex; flex-direction: column; gap: 8px; padding-top: 2px; }",
    ".hierarchy-content-section + .hierarchy-content-section { border-top: 1px solid color-mix(in oklab, var(--sb-border) 70%, transparent); padding-top: 12px; }",
    ".hierarchy-content-note { border: 1px solid color-mix(in oklab, var(--sb-warning) 45%, var(--sb-border)); background: color-mix(in oklab, var(--sb-warning) 8%, var(--sb-surface)); border-radius: 8px; padding: 10px 12px; display: flex; flex-direction: column; gap: 6px; }",
    ".card-surface, .kanban-card { width: 100%; box-sizing: border-box; border: 1px solid var(--sb-border); border-radius: 10px; background: var(--sb-surface); padding: 10px 12px; display: flex; flex-direction: column; gap: 10px; }",
    ".card-surface-header, .kanban-card-header { display: flex; flex-direction: column; gap: 8px; }",
    ".card-surface-title-row { display: flex; align-items: flex-start; gap: 8px; }",
    ".card-surface-header-actions { display: inline-flex; align-items: center; gap: 6px; margin-left: auto; flex-shrink: 0; }",
    ".card-surface-title, .kanban-card-title { flex: 1; display: flex; align-items: center; gap: 6px; text-align: left; border: none; background: transparent; padding: 0; font: inherit; color: inherit; cursor: pointer; min-width: 0; }",
    ".card-surface-title .card-title, .kanban-card-title .card-title { font-weight: var(--sb-weight-semibold); }",
    ".card-due-date { align-self: flex-start; font-size: var(--sb-font-xs); line-height: var(--sb-line-tight); color: var(--sb-muted-strong); font-weight: var(--sb-weight-semibold); }",
    ".card-due-date-overdue { color: var(--sb-error-text); font-weight: var(--sb-weight-bold); }",
    ".card-surface-body, .kanban-card-body { display: flex; flex-direction: column; gap: 8px; }",
    ".card-surface-task-list, .kanban-card-tasks { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 6px; }",
    ".card-surface-task-row { margin: 0; padding: 0; list-style: none; }",
    ".card-surface-overflow { margin: 0; font-size: var(--sb-font-xs); color: var(--sb-muted); }",
    ".card-surface-empty { margin: 0; font-size: var(--sb-font-xs); color: var(--sb-muted); }",
    ".card-surface-status-items { display: flex; flex-wrap: wrap; gap: 6px; }",
    ".card-surface-footer { display: flex; justify-content: flex-end; gap: 8px; flex-wrap: wrap; }",
    ".hierarchy-card-wrapper { display: flex; flex-direction: column; gap: 6px; width: 100%; }",
    ".hierarchy-card-wrapper .card-surface-status-items { gap: 5px; }",
    ".hierarchy-card-wrapper .card-surface { min-width: 0; max-width: 100%; }",
    ".hierarchy-delivery-card { display: grid; grid-template-columns: auto auto minmax(0, 1fr) auto; align-items: center; gap: 8px; width: 100%; min-width: 0; border: 1px solid var(--sb-border); border-radius: 10px; background: var(--sb-surface); padding: 9px 10px; }",
    ".hierarchy-card-toggle { display: inline-flex; align-items: center; justify-content: center; appearance: none; width: 28px; height: 28px; border: 1px solid transparent; border-radius: 8px; background: transparent; color: var(--sb-muted); cursor: pointer; flex-shrink: 0; }",
    ".hierarchy-card-toggle:hover { color: var(--sb-text); background: var(--sb-elevated); border-color: var(--sb-border); }",
    ".hierarchy-card-toggle:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; }",
    ".hierarchy-card-toggle-icon { display: inline-flex; transform: rotate(0deg); transition: transform 0.15s ease; font-size: 11px; line-height: 1; }",
    ".hierarchy-card-toggle[aria-expanded=\"false\"] .hierarchy-card-toggle-icon { transform: rotate(-90deg); }",
    ".hierarchy-card-swatch { width: 10px; height: 10px; border-radius: 999px; background: var(--sb-card-accent, var(--sb-border)); box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 70%, var(--sb-border)); }",
    ".hierarchy-card-swatch.card-border-gray { --sb-card-accent: var(--sb-card-gray); }",
    ".hierarchy-delivery-card-main { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".hierarchy-delivery-card-title-row { display: flex; align-items: center; gap: 8px; min-width: 0; }",
    ".hierarchy-delivery-card-title { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: var(--sb-font-base); font-weight: var(--sb-weight-semibold); color: var(--sb-text); }",
    ".hierarchy-delivery-card-progress { max-width: 180px; }",
    ".hierarchy-card-status-items { display: inline-flex; align-items: center; gap: 5px; flex-wrap: wrap; margin-left: auto; }",
    ".hierarchy-card-status-chip { display: inline-flex; align-items: center; min-height: 21px; border: 1px solid var(--sb-border); border-radius: 999px; padding: 1px 7px; font-size: 11px; font-weight: var(--sb-weight-medium); line-height: var(--sb-line-tight); color: var(--sb-muted-strong); background: var(--sb-elevated); }",
    ".hierarchy-card-status-chip.blocked { border-color: color-mix(in oklab, var(--sb-error) 34%, var(--sb-border)); color: var(--sb-error); background: color-mix(in oklab, var(--sb-error) 6%, var(--sb-surface)); }",
    ".hierarchy-card-status-chip.no-progress, .hierarchy-card-status-chip.empty { border-color: color-mix(in oklab, var(--sb-warning) 38%, var(--sb-border)); color: color-mix(in oklab, var(--sb-warning) 70%, var(--sb-text)); background: color-mix(in oklab, var(--sb-warning) 8%, var(--sb-surface)); }",
    ".hierarchy-card-status-chip.complete { border-color: color-mix(in oklab, var(--sb-success) 34%, var(--sb-border)); color: var(--sb-success); background: color-mix(in oklab, var(--sb-success) 7%, var(--sb-surface)); }",
    ".hierarchy-card-actions { display: inline-flex; align-items: center; gap: 5px; flex-wrap: wrap; justify-content: flex-end; }",
    ".hierarchy-card-kanban { gap: 4px; padding-inline: 8px; white-space: nowrap; }",
    ".hierarchy-card-tasks-panel { margin-left: 36px; border: 1px solid color-mix(in oklab, var(--sb-border) 72%, transparent); border-radius: 10px; background: color-mix(in oklab, var(--sb-elevated) 76%, transparent); padding: 8px; }",
    ".hierarchy-card-tasks-list { display: flex; flex-direction: column; gap: 6px; }",
    ".hierarchy-card-tasks-empty { margin: 0; padding: 6px 8px; color: var(--sb-muted); font-size: var(--sb-font-sm); }",
    ".hierarchy-card-task-row .hierarchy-task-item { background: var(--sb-surface); }",
    ".hierarchy-cards-list { display: flex; flex-direction: column; gap: 6px; }",
    ".hierarchy-task-row { display: flex; width: 100%; }",
    ".hierarchy-task-item { width: 100%; background: var(--sb-surface); border-radius: 8px; }",
    ".hierarchy-task-content { min-width: 0; }",
    ".hierarchy-task-meta { gap: 8px; flex-wrap: wrap; }",
    ".hierarchy-task-status { font-size: var(--sb-font-xs); color: var(--sb-muted); border: 1px solid var(--sb-border); border-radius: 999px; padding: 1px 8px; background: var(--sb-elevated); }",
    ".hierarchy-task-action-slot { min-width: 36px; }",
    ".hierarchy-card-title { margin: 0; font-size: var(--sb-font-base); font-weight: var(--sb-weight-semibold); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".move-menu { position: relative; display: inline-flex; align-items: center; }",
    ".move-menu-trigger { display: inline-flex; align-items: center; gap: 6px; min-height: 28px; border: 1px solid var(--sb-border); border-radius: 999px; background: color-mix(in oklab, var(--sb-elevated) 92%, transparent); color: var(--sb-text); padding: 0 10px; font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); cursor: pointer; }",
    ".move-menu-trigger::after { content: \"▾\"; font-size: 10px; color: var(--sb-muted); }",
    ".move-menu-trigger:hover, .move-menu:focus-within .move-menu-trigger { border-color: var(--sb-primary); color: var(--sb-primary); }",
    ".move-menu-actions { position: absolute; right: 0; top: calc(100% + 6px); display: none; flex-direction: column; min-width: 180px; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 10px; padding: 6px; box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08); z-index: 8; }",
    ".move-menu:hover .move-menu-actions, .move-menu:focus-within .move-menu-actions { display: flex; }",
    ".move-menu-option { display: flex; justify-content: flex-start; width: 100%; text-align: left; border: none; background: transparent; border-radius: 8px; padding: 6px 8px; color: var(--sb-text); cursor: pointer; }",
    ".move-menu-option:hover, .move-menu-option:focus-visible { background: var(--sb-elevated); }",
    "@media (max-width: 768px) { .hierarchy-item-header { grid-template-columns: 1fr; } }",
    "@media (max-width: 768px) { .hierarchy-item-meta { justify-self: start; } }",
    "@media (max-width: 1024px) { .hierarchies-shell { grid-template-columns: 1fr; } .hierarchies-list-pane { position: static; } }",
    "@media (max-width: 768px) { .hierarchy-summary-grid { grid-template-columns: 1fr; gap: 14px; } .hierarchy-summary-list .detail-row { grid-template-columns: 1fr; gap: 4px; } }",
    "@media (max-width: 768px) { .hierarchies-filter-row { justify-content: flex-start; } .hierarchy-detail-pane { min-width: 0; max-width: 100%; } .hierarchy-detail-main, .hierarchy-detail-empty { min-width: 0; max-width: 100%; padding: 12px; } .hierarchy-detail-content, .hierarchy-content-section, .hierarchy-card-wrapper { min-width: 0; max-width: 100%; } .hierarchy-detail-header-main { flex-direction: column; } .hierarchy-detail-actions { width: 100%; justify-content: flex-start; } .hierarchy-summary-toggle { align-items: flex-start; flex-direction: column; } .hierarchy-summary-meta { max-width: 100%; overflow: hidden; text-overflow: ellipsis; } .hierarchy-delivery-card { grid-template-columns: auto auto minmax(0, 1fr); align-items: flex-start; } .hierarchy-card-actions { grid-column: 3; justify-content: flex-start; } .hierarchy-card-tasks-panel { margin-left: 0; } .hierarchy-delivery-card-title-row { align-items: flex-start; flex-direction: column; gap: 5px; } .hierarchy-card-status-items { margin-left: 0; } .hierarchy-delivery-card-progress { max-width: 100%; } .hierarchy-card-wrapper .card-surface-title-row { flex-wrap: wrap; } .hierarchy-card-wrapper .card-surface-header-actions { margin-left: 0; } }",
    "@media (max-width: 640px) { .action-row { align-items: stretch; flex-direction: column; } .action-row-main { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); width: 100%; } .action-row-main .btn { width: 100%; justify-content: center; } .action-row-manage { width: 100%; justify-content: flex-end; margin-left: 0; } }",
    ".hierarchy-badge { font-size: var(--sb-font-xs); border: 1px solid color-mix(in oklab, var(--sb-success) 42%, var(--sb-border)); color: var(--sb-success-text); background: color-mix(in oklab, var(--sb-success) 10%, var(--sb-surface)); border-radius: 999px; padding: 1px 8px; }",
    ".hierarchies-state { color: var(--sb-muted); padding: 16px 4px; }",
    ".hierarchies-error { color: var(--sb-error); }",
    ".hierarchy-detail-content .detail-header { gap: 8px; }",
    ".hierarchy-detail-content .detail-title-row { margin-bottom: 6px; }",
    ".hierarchy-detail-summary { display: flex; flex-direction: column; gap: 8px; }",
    ".hierarchy-detail-progress-row { padding: 0 2px; }",
    ".hierarchy-detail-content .detail-header-block { padding-bottom: 8px; }",
    ".hierarchy-details-dialog .hierarchy-item-stats { gap: 10px; }",
    ".hierarchy-details-dialog .hierarchy-item-meta { gap: 10px; }",
    ".hierarchy-details-dialog .hierarchy-progress-percent { font-size: 13px; min-width: 40px; }",
    ".hierarchy-details-dialog .hierarchy-stat-pill { font-size: 12px; padding: 3px 9px; }",
    ".hierarchy-details-dialog .modal-tab.tab-active { box-shadow: inset 0 0 0 1px color-mix(in oklab, var(--sb-primary) 45%, var(--sb-border)); }",
    ".hierarchy-details-dialog .hierarchy-subsection { box-shadow: inset 0 1px 0 color-mix(in oklab, var(--sb-surface) 50%, transparent); }",
    ".hierarchy-details-dialog .hierarchy-card-title { font-size: 14px; line-height: 1.4; }",
    ".hierarchy-details-dialog .hierarchy-task-status { font-size: 12px; padding: 2px 9px; }",
    ".work-surface-header { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: end; gap: var(--sb-gap-group); padding: 10px 12px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); }",
    ".work-surface { display: flex; flex-direction: column; gap: var(--sb-gap-group); min-width: 0; }",
    ".work-surface-filters, .work-surface-state, .work-surface-content { min-width: 0; }",
    ".work-surface-copy { display: flex; flex-direction: column; gap: 4px; min-width: 0; }",
    ".work-surface-title { margin: 0; font-size: var(--sb-font-lg); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); color: var(--sb-text-strong); }",
    ".work-surface-purpose { margin: 0; max-width: 64ch; font-size: var(--sb-font-sm); line-height: var(--sb-line-body); color: var(--sb-muted-strong); }",
    ".work-surface-meta { display: flex; align-items: center; justify-content: flex-end; gap: var(--sb-gap-related); flex-wrap: wrap; min-width: 0; }",
    ".work-surface-summary { display: flex; align-items: center; justify-content: flex-end; gap: 6px; flex-wrap: wrap; min-width: 0; }",
    ".work-surface-summary.is-empty, .work-surface-actions.is-empty { display: none; }",
    ".work-surface-actions { display: inline-flex; align-items: center; justify-content: flex-end; gap: 8px; flex-wrap: wrap; }",
    ".work-surface-chip { display: inline-flex; align-items: baseline; gap: 5px; min-height: 26px; border: 1px solid var(--sb-border); border-radius: 999px; background: var(--sb-elevated); padding: 2px 9px; color: var(--sb-muted-strong); }",
    ".work-surface-chip.primary, .work-surface-chip.ongoing { border-color: color-mix(in oklab, var(--sb-primary) 34%, var(--sb-border)); color: var(--sb-primary); }",
    ".work-surface-chip.available, .work-surface-chip.success { border-color: color-mix(in oklab, var(--sb-success) 34%, var(--sb-border)); color: var(--sb-success); background: color-mix(in oklab, var(--sb-success) 6%, var(--sb-elevated)); }",
    ".work-surface-chip.claimed, .work-surface-chip.warning { border-color: color-mix(in oklab, var(--sb-warning) 38%, var(--sb-border)); color: var(--sb-warning-text); background: color-mix(in oklab, var(--sb-warning) 8%, var(--sb-elevated)); }",
    ".work-surface-chip.blocked { border-color: color-mix(in oklab, var(--sb-error) 36%, var(--sb-border)); color: var(--sb-error); background: color-mix(in oklab, var(--sb-error) 7%, var(--sb-elevated)); }",
    ".work-surface-chip-value { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); font-variant-numeric: tabular-nums; }",
    ".work-surface-chip-label { font-size: var(--sb-font-xs); }",
    ".plan-scope-shell { display: flex; flex-direction: column; gap: var(--sb-gap-related); min-width: 0; }",
    ".plan-scope-bar { display: flex; align-items: center; justify-content: space-between; gap: var(--sb-gap-group); flex-wrap: wrap; padding: 8px 10px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-lg); background: color-mix(in oklab, var(--sb-elevated) 72%, transparent); }",
    ".plan-scope-controls, .plan-mode-controls, .plan-closed-toggle { display: inline-flex; align-items: center; gap: 8px; min-width: 0; }",
    ".plan-scope-controls label, .plan-mode-label { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); color: var(--sb-muted-strong); }",
    ".plan-scope-controls select { min-height: 34px; max-width: 220px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); background: var(--sb-surface); color: var(--sb-text); padding: 6px 28px 6px 8px; font-size: var(--sb-font-sm); }",
    ".plan-card-scope-control { display: inline-grid; grid-template-columns: minmax(160px, 1fr) minmax(120px, auto); gap: 6px; align-items: center; min-width: 0; }",
    ".plan-card-scope-control input { min-height: 34px; min-width: 0; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); background: var(--sb-surface); color: var(--sb-text); padding: 6px 8px; font-size: var(--sb-font-sm); }",
    ".plan-mode-btn { min-height: 34px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); background: var(--sb-surface); color: var(--sb-text); padding: 6px 10px; font-size: var(--sb-font-sm); font-weight: var(--sb-weight-medium); cursor: pointer; }",
    ".plan-mode-btn:hover, .plan-mode-btn:focus-visible, .plan-scope-controls select:focus-visible, .plan-card-scope-control input:focus-visible { border-color: var(--sb-primary); outline: 2px solid color-mix(in oklab, var(--sb-primary) 28%, transparent); outline-offset: 1px; }",
    ".plan-mode-btn.is-active { border-color: color-mix(in oklab, var(--sb-primary) 42%, var(--sb-border)); background: var(--sb-primary-subtle-bg); color: var(--sb-primary); }",
    ".plan-closed-toggle { min-height: 34px; color: var(--sb-text); font-size: var(--sb-font-sm); }",
    ".plan-closed-toggle input { width: 16px; height: 16px; accent-color: var(--sb-primary); }",
    ".plan-filter-bar { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; min-width: 0; padding: 6px 10px; border: 1px solid color-mix(in oklab, var(--sb-border) 76%, transparent); border-radius: var(--sb-radius-lg); background: var(--sb-surface); }",
    ".plan-filter-control { display: inline-flex; align-items: center; gap: 6px; min-width: 0; color: var(--sb-muted-strong); font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); }",
    ".plan-filter-control select { min-height: 32px; max-width: 160px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); background: var(--sb-surface); color: var(--sb-text); padding: 5px 28px 5px 8px; font-size: var(--sb-font-sm); }",
    ".plan-filter-control select:focus-visible { border-color: var(--sb-primary); outline: 2px solid color-mix(in oklab, var(--sb-primary) 28%, transparent); outline-offset: 1px; }",
    ".plan-filter-search-chip { display: inline-flex; align-items: center; min-height: 26px; border: 1px solid color-mix(in oklab, var(--sb-primary) 28%, var(--sb-border)); border-radius: 999px; background: var(--sb-primary-subtle-bg); color: var(--sb-primary); padding: 2px 8px; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); }",
    ".plan-structure-view { display: flex; flex-direction: column; gap: var(--sb-gap-section); min-width: 0; height: 100%; }",
    ".plan-structure-split { display: grid; grid-template-columns: minmax(0, 1.35fr) minmax(280px, 0.85fr); gap: var(--sb-gap-related); align-items: start; min-width: 0; }",
    ".plan-structure-table { min-width: 0; }",
    ".plan-cell-tree { min-width: 260px; }",
    ".plan-tree-cell { display: grid; grid-template-columns: 20px minmax(0, 1fr) auto; gap: 8px; align-items: start; min-height: 40px; min-width: 0; }",
    ".plan-tree-toggle { display: inline-flex; align-items: center; justify-content: center; width: 20px; min-height: 24px; border: 0; border-radius: var(--sb-radius-sm); background: transparent; color: var(--sb-muted); padding: 0; cursor: pointer; }",
    ".plan-tree-toggle:hover, .plan-tree-toggle:focus-visible { background: var(--sb-elevated); color: var(--sb-primary); outline: 2px solid color-mix(in oklab, var(--sb-primary) 24%, transparent); outline-offset: 1px; }",
    ".plan-tree-trigger { display: inline-flex; align-items: flex-start; min-width: 0; min-height: 24px; border: 0; background: transparent; color: var(--sb-text); padding: 0; text-align: left; cursor: pointer; }",
    ".plan-tree-trigger:hover .plan-tree-title, .plan-tree-trigger:focus-visible .plan-tree-title { color: var(--sb-primary); }",
    ".plan-tree-marker { display: inline-flex; align-items: center; justify-content: center; width: 16px; height: 20px; color: var(--sb-muted); font-size: var(--sb-font-xs); }",
    ".plan-tree-leaf { display: inline-flex; align-items: center; justify-content: center; width: 20px; min-height: 24px; color: var(--sb-muted); font-size: var(--sb-font-xs); }",
    ".plan-tree-title { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); color: var(--sb-text-strong); overflow-wrap: anywhere; }",
    ".plan-tree-path { grid-column: 2 / -1; font-size: var(--sb-font-xs); line-height: var(--sb-line-tight); color: var(--sb-muted); overflow-wrap: anywhere; }",
    ".plan-tree-level { align-self: start; border: 1px solid color-mix(in oklab, var(--sb-border) 86%, transparent); border-radius: 999px; background: var(--sb-elevated); color: var(--sb-muted-strong); padding: 1px 7px; font-size: var(--sb-font-xs); white-space: nowrap; }",
    ".plan-phase { display: inline-flex; align-items: center; min-height: 24px; border: 1px solid var(--sb-border); border-radius: 999px; padding: 1px 8px; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); color: var(--sb-muted-strong); background: var(--sb-elevated); }",
    ".plan-phase.draft { border-color: color-mix(in oklab, var(--sb-muted) 36%, var(--sb-border)); }",
    ".plan-phase.active { border-color: color-mix(in oklab, var(--sb-primary) 40%, var(--sb-border)); color: var(--sb-primary); background: var(--sb-primary-subtle-bg); }",
    ".plan-phase.closed { border-color: color-mix(in oklab, var(--sb-success) 40%, var(--sb-border)); color: var(--sb-success); background: color-mix(in oklab, var(--sb-success) 7%, var(--sb-elevated)); }",
    ".plan-rollup { display: flex; flex-direction: column; gap: 2px; min-width: 92px; }",
    ".plan-rollup-main { font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); color: var(--sb-text-strong); font-variant-numeric: tabular-nums; }",
    ".plan-rollup-muted { font-size: var(--sb-font-xs); color: var(--sb-muted); font-variant-numeric: tabular-nums; }",
    ".plan-task-count, .plan-due-date { font-size: var(--sb-font-sm); color: var(--sb-muted-strong); white-space: nowrap; font-variant-numeric: tabular-nums; }",
    ".plan-due-date.is-empty { color: var(--sb-muted); }",
    ".plan-row-actions { display: flex; justify-content: flex-end; gap: 5px; flex-wrap: wrap; min-width: 150px; }",
    ".plan-action-btn { min-height: 28px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-md); background: var(--sb-surface); color: var(--sb-text); padding: 3px 7px; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-medium); cursor: pointer; }",
    ".plan-action-btn:hover, .plan-action-btn:focus-visible { border-color: var(--sb-primary); color: var(--sb-primary); }",
    ".plan-action-btn[disabled] { cursor: not-allowed; opacity: 0.48; color: var(--sb-muted); }",
    ".plan-structure-detail { position: sticky; top: var(--sb-gap-related); display: flex; flex-direction: column; gap: var(--sb-gap-related); min-width: 0; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-lg); background: var(--sb-surface); padding: 12px; }",
    ".plan-detail-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--sb-gap-related); min-width: 0; }",
    ".plan-detail-heading h4 { margin: 0; font-size: var(--sb-font-md); line-height: var(--sb-line-title); color: var(--sb-text-strong); overflow-wrap: anywhere; }",
    ".plan-detail-heading span, .plan-detail-path { font-size: var(--sb-font-xs); color: var(--sb-muted); overflow-wrap: anywhere; }",
    ".plan-detail-section-title { margin: 0; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-bold); line-height: var(--sb-line-tight); color: var(--sb-muted-strong); text-transform: uppercase; }",
    ".plan-detail-list { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".plan-detail-list li { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; align-items: center; min-height: 34px; border: 1px solid color-mix(in oklab, var(--sb-border) 82%, transparent); border-radius: var(--sb-radius-md); background: var(--sb-elevated); padding: 6px 8px; }",
    ".plan-detail-link { border: 0; background: transparent; color: var(--sb-text-strong); padding: 0; text-align: left; font-size: var(--sb-font-sm); font-weight: var(--sb-weight-semibold); cursor: pointer; overflow-wrap: anywhere; }",
    ".plan-detail-link:hover, .plan-detail-link:focus-visible { color: var(--sb-primary); }",
    ".plan-detail-task-title { font-size: var(--sb-font-sm); color: var(--sb-text); overflow-wrap: anywhere; }",
    ".plan-detail-list li span:last-child { font-size: var(--sb-font-xs); color: var(--sb-muted); white-space: nowrap; }",
    ".plan-detail-empty p { margin: 0; color: var(--sb-muted-strong); font-size: var(--sb-font-sm); }",
    ".plan-detail-rollup, .plan-detail-actions { display: flex; flex-wrap: wrap; gap: 6px; min-width: 0; }",
    ".plan-structure-empty { display: flex; flex-direction: column; align-items: flex-start; gap: 8px; min-height: 180px; border: 1px dashed var(--sb-border); border-radius: var(--sb-radius-lg); background: var(--sb-surface); color: var(--sb-muted-strong); padding: 18px; }",
    ".plan-structure-empty h3 { margin: 0; font-size: var(--sb-font-lg); color: var(--sb-text-strong); }",
    ".card-tree-scope-shell { display: flex; flex-direction: column; gap: var(--sb-gap-section); min-width: 0; }",
    ".card-tree-header { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--sb-gap-group); padding: 10px 12px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); min-width: 0; }",
    ".card-tree-header h3 { margin: 0; font-size: var(--sb-font-lg); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); color: var(--sb-text-strong); }",
    ".card-tree-subtitle { display: block; margin-top: 4px; max-width: 68ch; font-size: var(--sb-font-sm); line-height: var(--sb-line-body); color: var(--sb-muted-strong); }",
    ".card-tree-header .scope-toggle-btn { flex-shrink: 0; border: 1px solid var(--sb-border); border-radius: 8px; background: var(--sb-surface); color: var(--sb-text); font-weight: var(--sb-weight-semibold); }",
    ".card-tree-header .scope-toggle-btn:hover { border-color: var(--sb-primary); color: var(--sb-primary); }",
    ".card-tree-section, .card-tree-state-group, .card-tree-task-group { display: flex; flex-direction: column; gap: 8px; min-width: 0; }",
    ".card-tree-section { padding: 12px; border: 1px solid var(--sb-border); border-radius: 8px; background: color-mix(in oklab, var(--sb-elevated) 82%, transparent); }",
    ".card-tree-section-title, .card-tree-state-group h4, .card-tree-task-group h4, .card-tree-profile h4, .card-tree-empty h4 { margin: 0; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-bold); line-height: var(--sb-line-tight); letter-spacing: var(--sb-letter-label); text-transform: uppercase; color: var(--sb-muted-strong); }",
    ".card-tree-card-scope { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: var(--sb-gap-related); min-width: 0; }",
    ".card-tree-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 8px; min-width: 0; }",
    ".card-tree-grid-dense { grid-template-columns: repeat(auto-fill, minmax(150px, 1fr)); }",
    ".card-tree-card, .card-tree-task { display: flex; width: 100%; min-width: 0; text-align: left; cursor: pointer; border: 1px solid var(--sb-border); border-radius: 8px; background: var(--sb-surface); color: var(--sb-text); }",
    ".card-tree-card { flex-direction: column; gap: 5px; min-height: 72px; padding: 10px 12px; }",
    ".card-tree-card:hover, .card-tree-task:hover { border-color: var(--sb-primary); background: color-mix(in oklab, var(--sb-primary) 5%, var(--sb-surface)); }",
    ".card-tree-card-title { font-size: var(--sb-font-base); font-weight: var(--sb-weight-semibold); line-height: var(--sb-line-title); color: var(--sb-text-strong); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".card-tree-card-meta { font-size: var(--sb-font-xs); color: var(--sb-muted); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".card-tree-task-list { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".card-tree-task { align-items: center; min-height: 34px; padding: 7px 10px; font-size: var(--sb-font-sm); line-height: var(--sb-line-title); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".card-tree-empty { display: flex; flex-direction: column; gap: 5px; padding: 12px; border: 1px dashed var(--sb-border); border-radius: 8px; background: var(--sb-surface); color: var(--sb-muted); min-width: 0; }",
    ".card-tree-empty span { font-size: var(--sb-font-sm); line-height: var(--sb-line-body); }",
    "@media (max-width: 1024px) { .plan-structure-split { grid-template-columns: 1fr; } .plan-structure-detail { position: static; } }",
    "@media (max-width: 768px) { .plan-tree-trigger { grid-template-columns: 16px minmax(0, 1fr); min-height: 44px; } .plan-tree-level { grid-column: 2; justify-self: start; } .plan-detail-heading, .plan-detail-list li { grid-template-columns: 1fr; } .plan-row-actions { justify-content: flex-start; min-width: 0; } .plan-action-btn { min-height: 36px; } .card-tree-header { flex-direction: column; align-items: stretch; } .card-tree-header .scope-toggle-btn { min-height: 44px; } .card-tree-grid, .card-tree-grid-dense, .card-tree-card-scope { grid-template-columns: 1fr; } .card-tree-card-title, .card-tree-card-meta, .card-tree-task { white-space: normal; } }",
    ".pool-view { display: flex; flex-direction: column; gap: var(--sb-gap-section); margin-top: var(--sb-gap-related); }",
    ".pool-header-action { justify-self: end; font-weight: var(--sb-weight-semibold); }",
    "@media (max-width: 768px) { .pool-view { gap: var(--sb-gap-group); margin-top: var(--sb-gap-related); } .work-surface-header { grid-template-columns: 1fr; align-items: start; gap: var(--sb-gap-related); padding-bottom: var(--sb-gap-related); } .work-surface-meta, .work-surface-summary, .work-surface-actions { justify-content: flex-start; } .pool-header-action { min-height: 44px; } }",
    ".grouped-list { display: flex; flex-direction: column; gap: 12px; }",
    ".grouped-list-empty { text-align: center; color: var(--sb-muted); padding: 40px 20px; }",
    ".card-group { background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; overflow: hidden; }",
    ".card-group-header { display: flex; align-items: center; gap: 10px; width: 100%; padding: 12px 16px; background: transparent; border: none; cursor: pointer; text-align: left; }",
    ".card-group-header:hover { background: var(--sb-surface); }",
    ".expand-icon { display: inline-flex; align-items: center; justify-content: center; font-size: 12px; line-height: 1; color: var(--sb-muted); width: 16px; height: 16px; flex: 0 0 16px; transform: rotate(0deg); transition: transform 0.12s ease; }",
    ".expand-icon.is-expanded { transform: rotate(90deg); }",
    ".card-title { flex: 1; font-weight: var(--sb-weight-medium); }",
    ".card-progress { font-size: var(--sb-font-base); color: var(--sb-muted); font-variant-numeric: tabular-nums; }",
    ".card-color-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }",
    ".card-task-list { list-style: none; margin: 0; padding: 0 16px 12px 16px; display: flex; flex-direction: column; gap: 6px; }",
    ".task-item-content { flex: 1; background: transparent; border: none; cursor: pointer; text-align: left; display: flex; justify-content: space-between; align-items: center; gap: 8px; padding: 0; }",
    ".task-status { font-size: var(--sb-font-sm); color: var(--sb-muted); }",
    ".task-status-muted { font-size: var(--sb-font-sm); color: var(--sb-muted); }",
    ".task-claimed-by { font-size: var(--sb-font-sm); color: var(--sb-muted); font-style: italic; display: inline-flex; align-items: center; gap: 4px; }",
    ".task-claimed-icon { display: inline-flex; align-items: center; }",
    ".btn-claim { background: var(--sb-success-fill); color: var(--sb-inverse); border-color: var(--sb-success-fill); }",
    ".btn-claim.btn-icon { padding: 6px; border-radius: 6px; display: flex; align-items: center; justify-content: center; min-width: 28px; min-height: 28px; }",
    ".btn-claim.btn-icon:hover { background: color-mix(in oklab, var(--sb-success-fill) 86%, oklch(0% 0 0)); }",
    ".kanban-view { display: flex; flex-direction: column; gap: var(--sb-gap-section); min-width: 0; height: 100%; }",
    ".kanban-board { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: var(--sb-gap-related); align-items: start; min-height: 400px; overflow-x: auto; padding-bottom: 2px; }",
    ".kanban-column { background: var(--sb-bg); border: 1px solid var(--sb-border); border-radius: 12px; display: flex; flex-direction: column; min-width: 0; min-height: 200px; }",
    ".kanban-column.pendiente { border-top: 3px solid var(--sb-muted); background: color-mix(in oklab, var(--sb-bg) 94%, var(--sb-muted)); }",
    ".kanban-column.claimed { border-top: 3px solid var(--sb-warning); background: color-mix(in oklab, var(--sb-bg) 94%, var(--sb-warning)); }",
    ".kanban-column.en-curso { border-top: 3px solid var(--sb-primary); background: color-mix(in oklab, var(--sb-bg) 94%, var(--sb-primary)); }",
    ".kanban-column.cerrada { border-top: 3px solid var(--sb-success); background: color-mix(in oklab, var(--sb-bg) 94%, var(--sb-success)); }",
    ".kanban-column-header { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 10px 12px; border-bottom: 1px solid var(--sb-border); }",
    ".kanban-column-title { display: flex; align-items: center; gap: 8px; }",
    ".kanban-column-icon { display: inline-flex; align-items: center; justify-content: center; color: var(--sb-muted); }",
    ".kanban-column-header h4 { margin: 0; font-size: var(--sb-font-md); font-weight: var(--sb-weight-semibold); }",
    ".column-count { font-size: var(--sb-font-sm); color: var(--sb-muted); background: var(--sb-elevated); padding: 2px 8px; border-radius: 10px; font-variant-numeric: tabular-nums; }",
    ".kanban-column-content { flex: 1; padding: 10px; display: flex; flex-direction: column; gap: 10px; overflow-y: auto; }",
    ".kanban-empty-column { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 8px; padding: 20px 14px; border: 1px dashed var(--sb-border); border-radius: 10px; color: var(--sb-muted-strong); text-align: center; min-height: 100px; }",
    ".kanban-empty-column .empty-icon { font-size: 24px; opacity: 0.6; }",
    ".kanban-empty-column .empty-text { font-size: var(--sb-font-base); }",
    ".kanban-card { padding: 10px; }",
    ".kanban-card-header { margin-bottom: 0; }",
    ".kanban-card-title { font-weight: var(--sb-weight-medium); }",
    ".kanban-card-title:hover { color: var(--sb-primary); }",
    ".kanban-card .card-surface-header-actions { gap: 4px; }",
    ".kanban-card .card-surface-header-actions .btn-icon:not(.btn-add-task) { background: transparent; border-color: transparent; color: var(--sb-muted); opacity: 0.48; }",
    ".kanban-card .card-surface-header-actions .btn-icon:not(.btn-add-task):hover, .kanban-card .card-surface-header-actions .btn-icon:not(.btn-add-task):focus-visible { background: var(--sb-elevated); border-color: var(--sb-border); color: var(--sb-primary); opacity: 1; }",
    ".kanban-card .card-surface-header-actions .btn-icon.btn-delete-blocked, .kanban-card .card-surface-header-actions .btn-icon.btn-delete-blocked:hover, .kanban-card .card-surface-header-actions .btn-icon.btn-delete-blocked:focus-visible { background: transparent; border-color: transparent; color: var(--sb-muted); opacity: 0.62; }",
    ".card-notes-indicator { font-weight: var(--sb-weight-semibold); color: var(--sb-warning-text); }",
    ".card-surface-description, .kanban-card-desc { font-size: var(--sb-font-sm); color: var(--sb-muted); line-height: var(--sb-line-body); }",
    ".kanban-card-progress { display: flex; align-items: center; gap: 8px; }",
    ".kanban-card-progress .progress-bar { flex: 1; }",
    ".kanban-card-health { display: flex; flex-wrap: wrap; gap: 5px; }",
    ".kanban-health-chip { display: inline-flex; align-items: baseline; gap: 4px; min-height: 22px; border: 1px solid color-mix(in oklab, var(--sb-border) 82%, transparent); border-radius: 999px; background: color-mix(in oklab, var(--sb-elevated) 88%, transparent); padding: 1px 7px; color: var(--sb-muted-strong); }",
    ".kanban-health-chip.blocked { border-color: color-mix(in oklab, var(--sb-error) 34%, var(--sb-border)); color: var(--sb-error); background: color-mix(in oklab, var(--sb-error) 6%, var(--sb-surface)); }",
    ".kanban-health-chip.ongoing { border-color: color-mix(in oklab, var(--sb-primary) 30%, var(--sb-border)); color: var(--sb-primary); }",
    ".kanban-health-value { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); font-variant-numeric: tabular-nums; }",
    ".kanban-health-label { font-size: 11px; }",
    ".progress-fill { width: 100%; height: 100%; background: var(--sb-success-fill); clip-path: inset(0 calc(100% - var(--progress-width, 0%)) 0 0); transition: clip-path var(--sb-transition-slow); }",
    ".progress-text { font-size: var(--sb-font-sm); color: var(--sb-muted); min-width: 40px; text-align: right; font-variant-numeric: tabular-nums; }",
    ".kanban-card-footer { display: flex; justify-content: flex-end; margin-top: var(--sb-space-md); padding-top: var(--sb-space-md); border-top: 1px solid var(--sb-border); }",
    ".kanban-card-footer .btn-add-task { border-color: color-mix(in oklab, var(--sb-primary) 40%, var(--sb-border)); color: var(--sb-primary); }",
    ".kanban-card-footer .btn-add-task:hover { background: color-mix(in oklab, var(--sb-primary) 10%, var(--sb-elevated)); border-color: var(--sb-primary); }",
    ".kanban-card-tasks { margin-top: 8px; padding-top: 8px; border-top: 1px solid var(--sb-border); display: flex; flex-direction: column; gap: 4px; }",
    ".kanban-task-item, .card-surface-task-compact { display: flex; align-items: center; gap: 6px; padding: 4px 6px; border-radius: 6px; font-size: var(--sb-font-sm); transition: background 0.15s; }",
    ".kanban-task-item.card-border-gray, .kanban-task-item.card-border-red, .kanban-task-item.card-border-orange, .kanban-task-item.card-border-yellow, .kanban-task-item.card-border-green, .kanban-task-item.card-border-blue, .kanban-task-item.card-border-purple, .kanban-task-item.card-border-pink { border: 1px solid color-mix(in oklab, var(--sb-card-accent, var(--sb-border)) 30%, var(--sb-border)); background: color-mix(in oklab, var(--sb-card-accent, var(--sb-surface)) 4%, transparent); }",
    ".kanban-task-item:hover { background: var(--sb-bg); }",
    ".kanban-task-content { flex: 1; display: flex; align-items: center; gap: 6px; background: transparent; border: none; cursor: pointer; text-align: left; padding: 0; min-width: 0; }",
    ".kanban-task-content:hover .task-title { color: var(--sb-primary); }",
    ".kanban-task-item .task-type-icon { flex-shrink: 0; display: flex; align-items: center; justify-content: center; width: 14px; height: 14px; }",
    ".kanban-task-item .task-title { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--sb-text); }",
    ".kanban-task-item .task-claimed-by { font-size: 10px; color: var(--sb-muted); flex-shrink: 0; max-width: 60px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".kanban-task-item.status-completed .task-title { text-decoration: line-through; color: var(--sb-muted); }",
    ".status-dot { width: 6px; height: 6px; border-radius: 50%; background: currentColor; }",
    ".btn-claim-mini { background: transparent; border: none; cursor: pointer; padding: 2px; border-radius: 4px; color: var(--sb-muted); opacity: 0; transition: opacity 0.15s, color 0.15s; display: flex; align-items: center; justify-content: center; }",
    ".kanban-task-item:hover .btn-claim-mini { opacity: 1; }",
    ".btn-claim-mini:hover { color: var(--sb-primary); background: var(--sb-surface); }",
    "@media (hover: none), (pointer: coarse) { .btn-claim-mini { opacity: 1; min-width: 32px; min-height: 32px; } }",
    "@media (max-width: 768px) { .kanban-view { gap: var(--sb-gap-group); } .plan-scope-bar { align-items: stretch; } .plan-scope-controls, .plan-mode-controls, .plan-closed-toggle, .plan-filter-control { width: 100%; } .plan-filter-bar { align-items: stretch; } .plan-scope-controls, .plan-filter-control { display: grid; grid-template-columns: auto minmax(0, 1fr); } .plan-scope-controls select, .plan-card-scope-control input, .plan-filter-control select { width: 100%; max-width: none; min-height: 44px; } .plan-card-scope-control { grid-column: 1 / -1; grid-template-columns: 1fr; } .plan-mode-controls { display: grid; grid-template-columns: auto repeat(2, minmax(0, 1fr)); } .plan-mode-btn { min-height: 44px; padding-inline: 6px; } .plan-closed-toggle { min-height: 44px; } .kanban-board { grid-template-columns: 1fr; overflow-x: visible; } }",
    ".capability-board { display: flex; flex-direction: column; gap: var(--sb-gap-section); min-height: 100%; min-width: 0; }",
    ".capability-board-row-summary { display: flex; justify-content: flex-end; flex-wrap: wrap; gap: 6px; min-width: 0; }",
    ".capability-summary-chip { display: inline-flex; align-items: baseline; gap: 5px; min-height: 24px; border: 1px solid color-mix(in oklab, var(--sb-border) 88%, transparent); border-radius: 999px; background: var(--sb-elevated); padding: 1px 8px; color: var(--sb-muted-strong); }",
    ".capability-summary-chip.blocked { border-color: color-mix(in oklab, var(--sb-error) 34%, var(--sb-border)); color: var(--sb-error); background: color-mix(in oklab, var(--sb-error) 6%, var(--sb-surface)); }",
    ".capability-summary-chip.ongoing { border-color: color-mix(in oklab, var(--sb-primary) 30%, var(--sb-border)); color: var(--sb-primary); }",
    ".capability-summary-value { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); font-variant-numeric: tabular-nums; }",
    ".capability-summary-label { font-size: 11px; }",
    ".capability-board-state { display: flex; align-items: center; justify-content: center; gap: 8px; min-height: 180px; border: 1px dashed var(--sb-border); border-radius: var(--sb-radius-lg); background: var(--sb-surface); color: var(--sb-muted-strong); padding: 18px; text-align: center; }",
    ".capability-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: var(--sb-gap-related); align-items: start; min-width: 0; }",
    ".capability-list-section { display: flex; flex-direction: column; gap: 8px; min-width: 0; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-lg); background: var(--sb-surface); padding: 10px; }",
    ".capability-list-section-header { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: var(--sb-gap-related); align-items: start; padding-bottom: 8px; border-bottom: 1px solid color-mix(in oklab, var(--sb-border) 72%, transparent); }",
    ".capability-list-section-header h4 { margin: 0; font-size: var(--sb-font-md); line-height: var(--sb-line-title); color: var(--sb-text-strong); }",
    ".capability-list-rows { display: flex; flex-direction: column; gap: 8px; min-width: 0; }",
    ".capability-list-row { display: flex; flex-direction: column; gap: 8px; min-width: 0; border: 1px solid color-mix(in oklab, var(--sb-border) 82%, transparent); border-radius: var(--sb-radius-md); background: color-mix(in oklab, var(--sb-elevated) 70%, transparent); padding: 8px; }",
    ".capability-list-row-header { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 8px; align-items: start; min-width: 0; }",
    ".capability-list-row-title { display: flex; align-items: center; gap: 7px; min-width: 0; }",
    ".capability-list-row-title h4 { margin: 0; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: var(--sb-font-sm); line-height: var(--sb-line-title); color: var(--sb-text); }",
    ".capability-row-swatch { width: 8px; height: 22px; border-left-width: 4px; border-left-style: solid; border-radius: 3px; flex: 0 0 auto; }",
    ".capability-list-task-preview { display: flex; flex-direction: column; gap: 6px; min-width: 0; }",
    ".capability-list-empty { min-height: 54px; display: flex; align-items: center; justify-content: center; border: 1px dashed var(--sb-border); border-radius: var(--sb-radius-md); color: var(--sb-muted-strong); font-size: var(--sb-font-sm); }",
    ".capability-matrix { display: flex; flex-direction: column; min-width: 640px; border: 1px solid var(--sb-border); border-radius: var(--sb-radius-lg); background: var(--sb-surface); overflow: auto; }",
    ".capability-matrix-row { display: grid; grid-template-columns: minmax(180px, 1.2fr) repeat(auto-fit, minmax(120px, 1fr)); min-width: max-content; border-bottom: 1px solid color-mix(in oklab, var(--sb-border) 78%, transparent); }",
    ".capability-matrix-row:last-child { border-bottom: 0; }",
    ".capability-matrix-header-row, .capability-matrix-total-row { background: color-mix(in oklab, var(--sb-elevated) 82%, transparent); }",
    ".capability-matrix-cell { display: flex; flex-direction: column; justify-content: center; gap: 2px; min-height: 52px; min-width: 0; border-right: 1px solid color-mix(in oklab, var(--sb-border) 78%, transparent); padding: 8px 10px; font-size: var(--sb-font-sm); color: var(--sb-text); }",
    ".capability-matrix-cell:last-child { border-right: 0; }",
    ".capability-matrix-header-cell { min-height: 40px; font-size: var(--sb-font-xs); font-weight: var(--sb-weight-bold); color: var(--sb-muted-strong); text-transform: uppercase; }",
    ".capability-matrix-card-cell { flex-direction: row; align-items: center; justify-content: flex-start; font-weight: var(--sb-weight-semibold); color: var(--sb-text-strong); }",
    ".capability-matrix-empty-cell { align-items: center; color: var(--sb-muted); background: color-mix(in oklab, var(--sb-bg) 65%, transparent); }",
    ".capability-matrix-total-cell, .capability-matrix-total-row .capability-matrix-cell { background: color-mix(in oklab, var(--sb-elevated) 72%, transparent); }",
    ".capability-matrix-total { font-size: var(--sb-font-md); font-weight: var(--sb-weight-bold); font-variant-numeric: tabular-nums; color: var(--sb-text-strong); }",
    ".capability-matrix-breakdown { font-size: 11px; color: var(--sb-muted-strong); white-space: nowrap; }",
    ".capability-board .task-item { gap: 6px; padding: 7px 8px; }",
    ".capability-board .task-item-content { min-width: 0; overflow: hidden; }",
    ".capability-board .task-item .task-title { min-width: 0; }",
    ".capability-board .task-item-meta { min-width: 0; max-width: 45%; flex: 0 1 auto; flex-wrap: nowrap; overflow: hidden; }",
    ".capability-board .task-claimed-by { min-width: 0; max-width: 100%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".capability-board .btn-claim { background: color-mix(in oklab, var(--sb-success-fill) 12%, var(--sb-surface)); border-color: color-mix(in oklab, var(--sb-success-fill) 34%, var(--sb-border)); color: var(--sb-success); }",
    ".capability-board .btn-claim:hover, .capability-board .btn-claim:focus-visible { background: color-mix(in oklab, var(--sb-success-fill) 20%, var(--sb-surface)); border-color: var(--sb-success); color: var(--sb-success); }",
    "@media (max-width: 1024px) { .capability-list-section-header, .capability-list-row-header { grid-template-columns: 1fr; } .capability-board-row-summary { justify-content: flex-start; } }",
    "@media (max-width: 768px) { .capability-list { grid-template-columns: 1fr; } .capability-matrix { min-width: 100%; } .capability-matrix-row { grid-template-columns: minmax(150px, 1.1fr) repeat(auto-fit, minmax(110px, 1fr)); } .capability-list-row-title h4 { white-space: normal; } }",
    ".drawer-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.42); z-index: 80; opacity: 0; pointer-events: none; transition: opacity 0.2s ease; }",
    ".drawer-overlay.open { opacity: 1; pointer-events: auto; }",
    ".drawer { position: fixed; top: 0; bottom: 0; width: min(360px, calc(100vw - 32px)); background: var(--sb-surface); z-index: 81; transform: translateX(-100%); transition: transform 0.24s cubic-bezier(0.32, 0.72, 0, 1); display: flex; flex-direction: column; box-shadow: var(--sb-shadow-modal); padding-top: env(safe-area-inset-top); padding-bottom: env(safe-area-inset-bottom); }",
    ".drawer.right { right: 0; left: auto; transform: translateX(100%); }",
    ".drawer.open { transform: translateX(0); }",
    ".drawer-header { display: flex; align-items: center; justify-content: flex-end; min-height: 56px; padding: 8px 12px; border-bottom: 1px solid var(--sb-border); background: var(--sb-surface-2); }",
    ".drawer-content { flex: 1; overflow-y: auto; padding: 12px; overscroll-behavior: contain; }",
    ".drawer-close { background: transparent; border: none; font-size: 24px; cursor: pointer; color: var(--sb-muted); min-width: 44px; min-height: 44px; display: inline-flex; align-items: center; justify-content: center; }",
    ".mini-task-bar { position: fixed; bottom: 0; left: 0; right: 0; background: var(--sb-primary); color: var(--sb-inverse); padding: 12px 16px; display: none; align-items: center; gap: 12px; z-index: 90; }",
    "@media (max-width: 768px) { .mini-task-bar.visible { display: flex; } }",
    ".mini-task-bar .task-title { flex: 1; font-weight: var(--sb-weight-medium); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
    ".mini-task-bar .task-timer { font-family: var(--sb-font-mono); font-variant-numeric: tabular-nums; font-weight: var(--sb-weight-semibold); }",
    ".mobile-header { display: none; align-items: center; justify-content: space-between; padding: 12px 16px; background: var(--sb-surface); border-bottom: 1px solid var(--sb-border); }",
    "@media (max-width: 768px) { .mobile-header { display: flex; } }",
    ".menu-hamburger, .menu-user { background: transparent; border: none; font-size: 24px; cursor: pointer; padding: 8px; }",
  ]
}
