//// Auto-split CSS chunk: pool

/// Provides pool CSS chunk.
pub fn css() -> List(String) {
  [
    ".task-card { background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 12px; overflow: hidden; position: relative; }",
    ".task-card:hover, .task-card:focus-within { z-index: 10; overflow: visible; box-shadow: 0 10px 30px rgba(0,0,0,0.18); }",
    ".task-card-top { position: absolute; top: 8px; left: 8px; right: 8px; display: flex; justify-content: space-between; gap: 6px; align-items: center; z-index: 2; }",
    ".task-card-type-icon { display: none; }",
    ".task-card-actions-left { display: flex; gap: 6px; align-items: center; flex-shrink: 0; }",
    ".task-card-actions-right { display: flex; gap: 6px; align-items: center; flex-shrink: 0; }",
    ".task-card-body { height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; gap: 6px; padding: 10px 10px 10px 10px; padding-top: 40px; box-sizing: border-box; }
.task-card-center { display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px; }
.task-card-center-icon { width: 28px; height: 28px; display: inline-flex; align-items: center; justify-content: center; opacity: 0.9; }",
    ".task-card-title { width: 100%; font-weight: 700; font-size: 13px; line-height: 1.15; text-align: center; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }",
    ".task-card.highlight { border: 2px solid var(--sb-primary); }",
    ".is-highlight-source { border-color: color-mix(in oklab, var(--sb-warning) 65%, var(--sb-border)) !important; box-shadow: 0 0 0 2px color-mix(in oklab, var(--sb-warning) 25%, transparent) !important; }",
    ".is-highlight-target { border-color: color-mix(in oklab, var(--sb-warning) 55%, var(--sb-border)) !important; box-shadow: 0 0 0 2px color-mix(in oklab, var(--sb-warning) 18%, transparent) !important; }",
    ".is-highlight-dimmed { opacity: 0.55; }",
    ".highlight-warning { outline: 0; }",
    ".highlight-info { outline: 0; }",
    ".highlight-success { outline: 0; }",
    ".task-card .secondary-action { display: inline-flex; opacity: 0.65; }",
    ".task-card:hover .secondary-action, .task-card:focus-within .secondary-action { opacity: 1; }",
    ".task-card-preview { position: absolute; top: 0; left: calc(100% + 8px); width: 320px; max-width: min(420px, calc(100vw - 24px)); background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 12px; padding: 12px 14px; box-shadow: 0 10px 30px rgba(0,0,0,0.18); opacity: 0; transform: scale(0.98); transition: opacity 120ms ease, transform 120ms ease; transition-delay: 200ms; pointer-events: auto; z-index: 20; }
.task-card.preview-left .task-card-preview { left: auto; right: calc(100% + 8px); }",
    ".task-preview-grid { display: grid; grid-template-columns: auto 1fr; column-gap: 10px; row-gap: 6px; align-items: baseline; }",
    ".task-preview-label { color: var(--sb-muted); font-size: 12px; }",
    ".task-preview-label-strong { color: var(--sb-text); font-weight: 600; }",
    ".task-preview-value { font-size: 12px; text-align: left; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".task-preview-description { white-space: normal; line-height: 1.4; }",
    ".task-preview-extras { display: flex; flex-direction: column; gap: 8px; margin-top: 10px; }",
    ".task-preview-section { display: flex; flex-direction: column; gap: 6px; padding-top: 6px; border-top: 1px dashed var(--sb-border); }",
    ".task-preview-section-title { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; color: var(--sb-muted); }",
    ".task-preview-list { display: flex; flex-direction: column; gap: 4px; list-style: disc; margin: 0; padding-left: 16px; }",
    ".task-preview-list-item { margin: 0; }",
    ".task-preview-blocked-list { display: flex; flex-direction: column; gap: 4px; }",
    ".task-preview-blocked-item { font-size: 12px; color: var(--sb-text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
    ".task-preview-blocked-hidden-note { font-size: 11px; color: var(--sb-muted); margin-top: 4px; display: inline-block; }",
    ".task-preview-notes { display: flex; flex-direction: column; gap: 6px; }",
    ".task-preview-note { display: flex; flex-direction: column; gap: 2px; }",
    ".task-preview-note-meta { font-size: 11px; color: var(--sb-muted); }",
    ".task-preview-note-content { font-size: 12px; color: var(--sb-text); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
    ".task-preview-actions { margin-top: 10px; display: flex; justify-content: flex-end; }",
    ".task-preview-btn { font-size: 12px; }",
    ".task-preview-badge { display: inline-flex; align-items: center; padding: 2px 8px; border-radius: 999px; border: 1px solid var(--sb-border); background: color-mix(in oklab, var(--sb-elevated) 70%, transparent); font-weight: 600; }",
    ".task-preview-badge-available { border-color: color-mix(in oklab, var(--sb-primary) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-primary) 12%, var(--sb-elevated)); }",
    ".task-preview-badge-claimed { border-color: color-mix(in oklab, var(--sb-info) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-info) 12%, var(--sb-elevated)); }",
    ".task-preview-badge-ongoing { border-color: color-mix(in oklab, var(--sb-warning) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-warning) 14%, var(--sb-elevated)); }",
    ".task-preview-badge-completed { border-color: color-mix(in oklab, var(--sb-success) 60%, var(--sb-border)); background: color-mix(in oklab, var(--sb-success) 12%, var(--sb-elevated)); }",
    ".task-card-preview::before { content: \"\"; position: absolute; left: -8px; top: 50%; transform: translateY(-50%); border-width: 8px 8px 8px 0; border-style: solid; border-color: transparent var(--sb-elevated) transparent transparent; }",
    ".task-card-preview::after { content: \"\"; position: absolute; left: -9px; top: 50%; transform: translateY(-50%); border-width: 9px 9px 9px 0; border-style: solid; border-color: transparent var(--sb-border) transparent transparent; }",
    ".task-card.preview-left .task-card-preview::before { left: auto; right: -8px; border-width: 8px 0 8px 8px; border-color: transparent transparent transparent var(--sb-elevated); }",
    ".task-card.preview-left .task-card-preview::after { left: auto; right: -9px; border-width: 9px 0 9px 9px; border-color: transparent transparent transparent var(--sb-border); }",
    ".task-card:hover .task-card-preview { opacity: 1; transform: scale(1); transition-delay: 350ms; }",
    ".task-card:focus-within .task-card-preview { opacity: 1; transform: scale(1); transition-delay: 0ms; }",
    ".task-card.touch-preview .task-card-preview { opacity: 1; transform: scale(1); transition-delay: 0ms; }",
    ".drag-handle { cursor: grab; user-select: none; padding: 0; border: 1px solid var(--sb-border); border-radius: 8px; background: transparent; color: var(--sb-muted); display: inline-flex; align-items: center; justify-content: center; min-width: 28px; min-height: 28px; line-height: 0; }",
    ".drag-handle:hover { border-color: var(--sb-primary); }
.drag-handle:active { cursor: grabbing; }",
    ".task-list { display: flex; flex-direction: column; gap: 8px; }",
    ".task-row { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; padding: 10px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); }",
    ".task-row-title { font-weight: 700; display: flex; align-items: center; gap: 6px; }",
    ".task-row-meta { color: var(--sb-muted); font-size: 0.9em; }",
    ".task-row-actions { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; justify-content: flex-end; }",
    ".skills-list { display: flex; flex-direction: column; gap: 6px; }",
    ".skill-row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 10px; border: 1px solid var(--sb-border); border-radius: 12px; background: var(--sb-elevated); }",
    ".skill-name { font-weight: 600; }",
    // Now Working section in right panel (unified layout)
    ".now-working-section { padding: 12px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 10px; margin-bottom: 12px; }",
    ".now-working-section.now-working-active { background: color-mix(in oklab, var(--sb-primary) 8%, var(--sb-elevated)); border-color: color-mix(in oklab, var(--sb-primary) 30%, var(--sb-border)); position: relative; }",
    ".now-working-section.now-working-active::before { content: ''; position: absolute; top: 12px; right: 12px; width: 8px; height: 8px; background: var(--sb-success); border-radius: 50%; animation: pulse-dot 2s ease-in-out infinite; }",
    "@keyframes pulse-dot { 0%, 100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.5; transform: scale(1.2); } }",
    ".now-working-task-title { font-weight: 600; margin-bottom: 4px; }",
    ".now-working-timer { font-variant-numeric: tabular-nums; color: var(--sb-muted); }",
    ".now-working-section .now-working-timer { font-size: 1.5rem; font-weight: 600; font-family: ui-monospace, monospace; text-align: center; margin: 8px 0; }",
    ".now-working-actions { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }",
    ".now-working-empty { display: flex; align-items: center; gap: 8px; justify-content: center; padding: 8px 0; color: var(--sb-muted); font-style: italic; }",
    ".now-working-empty-icon { font-size: 1.2em; opacity: 0.7; }",
    ".now-working-section .now-working-actions { justify-content: center; }",
    // Multi-session support for EN CURSO panel
    ".now-working-multi { padding: 8px; }",
    ".now-working-multi::before { display: none; }",
    ".now-working-sessions { display: flex; flex-direction: column; gap: 8px; max-height: 240px; overflow-y: auto; }",
    ".now-working-session-item { display: flex; flex-direction: column; gap: 4px; padding: 10px 12px; background: var(--sb-surface); border: 1px solid var(--sb-border); border-radius: 8px; position: relative; }",
    ".now-working-session-item::before { content: ''; position: absolute; top: 10px; right: 10px; width: 6px; height: 6px; background: var(--sb-success); border-radius: 50%; animation: pulse-dot 2s ease-in-out infinite; }",
    ".now-working-session-item .now-working-task-title { font-size: 0.9rem; font-weight: 600; padding-right: 16px; }",
    ".now-working-session-item .now-working-timer { font-size: 1.1rem; font-weight: 600; font-family: ui-monospace, monospace; color: var(--sb-primary); }",
    ".now-working-session-item .now-working-actions { flex-direction: row; justify-content: flex-start; margin-top: 4px; }",
    // Task row active state
    ".task-row-active { background: color-mix(in oklab, var(--sb-primary) 10%, var(--sb-elevated)); border-color: var(--sb-primary); }",
    "@media (max-width: 640px) { .body { flex-direction: column; } .nav { width: 100%; } }",
  ]
}
