//// Auto-split CSS chunk: tables

/// Provides tables CSS chunk.
pub fn css() -> List(String) {
  [
    ".table { width: 100%; border-collapse: collapse; }",
    ".table th { text-align: left; color: var(--sb-muted-strong); font-weight: var(--sb-weight-bold); font-size: var(--sb-font-sm); line-height: var(--sb-line-tight); text-transform: uppercase; letter-spacing: var(--sb-letter-label); padding: 10px 12px; border-bottom: 2px solid var(--sb-border); background: var(--sb-surface); }",
    ".table-header { font-weight: var(--sb-weight-bold); font-size: var(--sb-font-sm); line-height: var(--sb-line-tight); text-transform: uppercase; letter-spacing: var(--sb-letter-label); }",
    ".table td { padding: 10px 12px; border-bottom: 1px solid var(--sb-border); vertical-align: middle; }",
    ".table tbody tr:nth-child(even) { background: color-mix(in oklab, var(--sb-surface) 50%, var(--sb-bg)); }",
    ".table tbody tr { transition: background var(--sb-transition-fast); }",
    ".table tbody tr:hover { background: var(--sb-elevated); }",
    ".table tbody tr.clickable { cursor: pointer; }",
    ".table tbody tr.clickable:hover { background: color-mix(in oklab, var(--sb-primary) 6%, var(--sb-elevated)); }",
    ".workflow-row > td { vertical-align: middle; }",
    ".expand-col { width: 40px; text-align: center; padding-left: 8px; padding-right: 4px; }",
    ".nested-table { margin-top: 4px; }",
    // Expansion rows for subtables
    ".expansion-row { background: var(--sb-surface) !important; }",
    ".expansion-row:hover { background: var(--sb-surface) !important; }",
    ".expansion-content { padding: 10px 12px; border: 1px solid color-mix(in oklab, var(--sb-primary) 28%, var(--sb-border)); border-radius: 10px; background: color-mix(in oklab, var(--sb-primary) 4%, var(--sb-surface)); margin: 6px 8px 8px 40px; }",
    ".expansion-content .table { background: var(--sb-elevated); border-radius: 8px; overflow: hidden; }",
    ".expansion-content .table th { background: var(--sb-surface); font-size: var(--sb-font-xs); padding: 8px 10px; }",
    ".expansion-content .table td { padding: 8px 10px; font-size: var(--sb-font-md); }",
    ".col-expand { width: 40px; text-align: center; }",
    ".cell-expand { text-align: center; }",
    ".btn-expand { background: transparent; border: none; padding: 4px 8px; cursor: pointer; font-size: var(--sb-font-sm); color: var(--sb-muted); border-radius: 4px; }",
    ".btn-expand:hover { background: var(--sb-elevated); color: var(--sb-text); }",
    ".automation-rule-list { display: flex; flex-direction: column; gap: 8px; width: 100%; min-width: 0; }",
    ".automation-rule-item { display: flex; flex-direction: column; min-width: 0; }",
    ".rule-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap: 12px; padding: 12px; border: 1px solid var(--sb-border); border-radius: 8px; background: var(--sb-surface); }",
    ".rule-row__main { display: flex; flex-direction: column; gap: 7px; min-width: 0; }",
    ".rule-row__title { display: flex; align-items: center; gap: 8px; min-width: 0; }",
    ".rule-row__name { color: var(--sb-text-strong); font-weight: var(--sb-weight-semibold); overflow-wrap: anywhere; }",
    ".rule-row__meta { display: flex; align-items: center; flex-wrap: wrap; gap: 6px; color: var(--sb-muted-strong); font-size: var(--sb-font-sm); line-height: var(--sb-line-tight); }",
    ".rule-row__metric { display: inline-flex; align-items: center; gap: 4px; padding: 2px 7px; border: 1px solid var(--sb-border); border-radius: 999px; background: color-mix(in oklab, var(--sb-elevated) 82%, var(--sb-surface)); font-variant-numeric: tabular-nums; }",
    ".rule-row__metric-label { color: var(--sb-muted); }",
    ".rule-row__metric-value { color: var(--sb-text); font-weight: var(--sb-weight-semibold); }",
    ".rule-row__actions { display: flex; align-items: center; justify-content: flex-end; }",
    // Templates expansion panel
    ".templates-expansion { padding: 12px 16px; background: color-mix(in oklab, var(--sb-primary) 4%, var(--sb-surface)); border-radius: 8px; margin: 8px 0 0; border: 1px solid color-mix(in oklab, var(--sb-primary) 28%, var(--sb-border)); }",
    ".templates-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 12px; }",
    ".templates-title { font-weight: var(--sb-weight-semibold); font-size: var(--sb-font-base); color: var(--sb-text); }",
    ".templates-empty { color: var(--sb-muted); font-size: var(--sb-font-base); font-style: italic; padding: 8px 0; }",
    ".templates-list { display: flex; flex-direction: column; gap: 6px; }",
    ".template-item { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 12px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 8px; }",
    ".template-name { font-size: var(--sb-font-base); font-weight: var(--sb-weight-medium); }",
    ".template-item .btn-danger { padding: 2px 8px; font-size: var(--sb-font-md); line-height: 1; border-radius: 4px; }",
    ".template-item .detaching { font-size: var(--sb-font-sm); color: var(--sb-muted); font-style: italic; }",
    // Story 4.10: AC2 - Clickable rule rows
    ".rule-row-expandable { cursor: pointer; transition: background 0.1s ease, border-color 0.1s ease; }",
    ".rule-row-expandable:hover { background: var(--sb-elevated); border-color: color-mix(in oklab, var(--sb-primary) 28%, var(--sb-border)); }",
    ".rule-row-expandable:focus-visible { outline: 2px solid var(--sb-primary); outline-offset: 2px; }",
    ".rule-row-expanded { background: var(--sb-surface); border-color: color-mix(in oklab, var(--sb-primary) 34%, var(--sb-border)); }",
    // AC2: Prevent row click on actions column
    ".cell-no-expand { pointer-events: auto; }",
    ".cell-no-expand * { position: relative; z-index: 1; }",
    // Story 4.10: AC5 - Expand icon (triangles)
    ".rule-expand-icon { display: inline-flex; align-items: center; justify-content: center; font-size: var(--sb-font-sm); color: var(--sb-muted); width: 16px; }",
    // Story 4.10: AC6-8 - Status indicators
    ".cell-status { text-align: center; width: 50px; }",
    ".rule-complete-indicator { color: var(--sb-success-text); }",
    ".rule-incomplete-indicator { color: var(--sb-warning-text); cursor: help; }",
    ".rule-inactive-indicator { color: var(--sb-muted); }",
    // Resource type cell with task type info
    ".cell-resource-type { white-space: nowrap; }",
    ".resource-type-task { display: inline-flex; align-items: center; }",
    ".resource-type-separator { color: var(--sb-muted); margin: 0 2px; }",
    ".task-type-inline { display: inline-flex; align-items: center; vertical-align: middle; }",
    ".task-type-inline svg { width: 14px; height: 14px; }",
    ".cell-rule-sentence { min-width: 260px; }",
    ".automation-rule-sentence { display: flex; flex-direction: column; gap: 3px; min-width: 0; line-height: var(--sb-line-body); }",
    ".automation-rule-sentence__when { color: var(--sb-text-strong); font-weight: var(--sb-weight-medium); overflow-wrap: anywhere; }",
    ".automation-rule-sentence__effect { color: var(--sb-muted-strong); font-size: var(--sb-font-sm); overflow-wrap: anywhere; }",
    ".automation-rule-sentence__badge { white-space: nowrap; }",
    // Story 4.10: AC4 - Attached template row with icon and priority
    ".attached-template-row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 8px 12px; background: var(--sb-elevated); border: 1px solid var(--sb-border); border-radius: 8px; }",
    ".attached-template-info { display: flex; align-items: center; gap: 8px; }",
    ".template-type-icon { display: inline-flex; opacity: 0.8; }",
    ".attached-template-name { font-size: var(--sb-font-base); font-weight: var(--sb-weight-medium); }",
    ".attached-template-meta { display: flex; align-items: center; gap: 8px; }",
    ".priority-badge { font-size: var(--sb-font-xs); font-weight: var(--sb-weight-semibold); color: var(--sb-muted); background: var(--sb-surface); padding: 2px 8px; border-radius: 4px; }",
    // Story 4.10: AC13 - Empathetic empty hint
    ".templates-empty-hint { display: flex; flex-direction: column; align-items: center; gap: 8px; padding: 16px 12px; text-align: center; color: var(--sb-muted); }",
    ".templates-empty-hint .hint-icon { color: var(--sb-primary); opacity: 0.6; }",
    ".templates-empty-hint p { margin: 0; font-size: var(--sb-font-base); line-height: var(--sb-line-body); }",
    // Story 4.10: AC12 - Radio buttons in modal
    ".radio-group { display: flex; flex-direction: column; gap: 6px; max-height: 240px; overflow-y: auto; }",
    ".template-radio-list { margin-bottom: 12px; }",
    ".radio-option { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 8px; border: 1px solid var(--sb-border); background: var(--sb-surface); cursor: pointer; transition: all 0.1s ease; }",
    ".radio-option:hover { border-color: var(--sb-primary); background: var(--sb-elevated); }",
    ".radio-option.selected { border-color: var(--sb-primary); background: color-mix(in oklab, var(--sb-primary) 10%, var(--sb-elevated)); }",
    ".radio-option input[type=radio] { width: 16px; height: 16px; margin: 0; accent-color: var(--sb-primary); cursor: pointer; }",
    ".radio-label { display: flex; align-items: center; gap: 8px; flex: 1; cursor: pointer; }",
    ".radio-label .template-name { font-size: var(--sb-font-md); font-weight: var(--sb-weight-medium); flex: 1; }",
    ".radio-label .template-priority { font-size: var(--sb-font-xs); color: var(--sb-muted); background: var(--sb-surface); padding: 2px 6px; border-radius: 4px; }",
    // Form hints
    ".form-hint { font-size: var(--sb-font-base); line-height: var(--sb-line-body); color: var(--sb-muted); margin-bottom: 8px; }",
    ".form-hint-secondary { display: flex; align-items: center; gap: 4px; font-size: var(--sb-font-sm); line-height: var(--sb-line-body); color: var(--sb-muted); margin-top: 8px; }",
    ".form-group .select { width: 100%; padding: 10px 12px; font-size: var(--sb-font-md); }",
    // Metric cells in tables
    ".metric-cell { text-align: center; }",
    ".metric { display: inline-block; padding: 2px 10px; border-radius: 12px; font-weight: var(--sb-weight-semibold); font-size: var(--sb-font-base); font-variant-numeric: tabular-nums; }",
    ".metric.applied { background: color-mix(in oklab, var(--sb-success) 15%, transparent); color: var(--sb-success-text); }",
    ".metric.suppressed { background: color-mix(in oklab, var(--sb-warning) 15%, transparent); color: var(--sb-warning-text); }",
    "@media (max-width: 640px) { .rule-row { grid-template-columns: minmax(0, 1fr); align-items: stretch; } .rule-row__title { align-items: flex-start; } .rule-row__actions { justify-content: flex-start; } .templates-expansion { padding: 10px 12px; } }",
    // Assignments view patterns (shared table/admin language)
    ".assignments-toolbar-card { padding: 10px 12px; margin-bottom: 12px; }",
    ".assignments-toolbar { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }",
    ".assignments-toggle-field { min-width: 260px; }",
    ".assignments-toggle { width: 100%; }",
    ".assignments-toggle .view-mode-btn { flex: 1; justify-content: center; min-height: 34px; padding: 6px 12px; }",
    ".assignments-search input { min-width: 240px; width: 100%; }",
    ".assignments-search { min-width: 260px; flex: 1 1 280px; }",
    ".assignments-table { margin-top: 4px; }",
    ".assignments-table th:first-child, .assignments-table td:first-child { padding-left: 12px; }",
    ".assignments-table th:last-child, .assignments-table td:last-child { padding-right: 12px; }",
    ".assignments-table-row > td { vertical-align: middle; }",
    ".assignments-primary-cell { width: 100%; }",
    ".assignments-meta-cell { white-space: nowrap; text-align: right; font-size: var(--sb-font-sm); color: var(--sb-muted); font-weight: var(--sb-weight-medium); font-variant-numeric: tabular-nums; }",
    ".assignments-card-title { display: flex; align-items: center; gap: 8px; font-weight: var(--sb-weight-semibold); min-width: 0; line-height: var(--sb-line-title); }",
    ".assignments-card-icon { display: inline-flex; }",
    ".assignments-card-title .badge { margin-left: 2px; }",
    ".assignments-card-body { display: flex; flex-direction: column; gap: 8px; margin-left: 0; border-left: 0; padding: 10px 0 0; }",
    ".assignments-card-body.expansion-content { background: color-mix(in oklab, var(--sb-primary) 4%, var(--sb-surface)); border: 1px solid color-mix(in oklab, var(--sb-primary) 32%, var(--sb-border)); border-radius: 10px; padding: 12px; margin: 6px 0 0; }",
    ".assignments-rows { display: flex; flex-direction: column; gap: 0; border: 1px solid var(--sb-border); border-radius: 10px; overflow: hidden; background: var(--sb-surface); }",
    ".assignments-row { display: grid; grid-template-columns: minmax(220px, 1fr) auto auto; align-items: center; gap: 8px; padding: 8px 10px; border-bottom: 1px solid var(--sb-border); background: var(--sb-surface); }",
    ".assignments-row:last-child { border-bottom: none; }",
    ".assignments-row-title { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
    ".assignments-row-actions { display: flex; gap: 6px; align-items: center; }",
    ".assignments-metrics { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0; }",
    ".assignments-metrics-item { font-size: var(--sb-font-sm); color: color-mix(in oklab, var(--sb-text) 82%, var(--sb-muted)); background: color-mix(in oklab, var(--sb-elevated) 85%, var(--sb-surface)); border: 1px solid color-mix(in oklab, var(--sb-border) 70%, var(--sb-text)); border-radius: 999px; padding: 4px 8px; }",
    ".assignments-inline-add { margin-top: 10px; padding: 10px; border-radius: 10px; border: 1px solid var(--sb-border); background: var(--sb-elevated); }",
    ".assignments-inline-add-row { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }",
    ".assignments-inline-add-label { font-size: var(--sb-font-sm); color: var(--sb-muted); }",
    ".assignments-inline-add-actions { display: flex; gap: 6px; }",
    ".assignments-card-body > .btn-sm { margin-top: 8px; }",
    ".assignments-inline-add input, .assignments-inline-add select, .assignments-row select { min-height: 32px; }",
    ".assignments-empty { color: var(--sb-muted); font-size: var(--sb-font-base); }",
    "@media (max-width: 768px) { .assignments-toolbar-card { padding: 8px 10px; } .assignments-toolbar { align-items: stretch; } .assignments-toggle-field, .assignments-search { min-width: 0; width: 100%; } .assignments-table thead { position: absolute; top: -9999px; left: -9999px; } .assignments-table tbody tr.assignments-table-row { display: block; padding: 10px 0; } .assignments-table tbody tr.assignments-table-row td { display: block; width: 100%; border: 0; padding: 4px 0; } .assignments-meta-cell { text-align: left; } .assignments-row { grid-template-columns: 1fr; align-items: stretch; } .assignments-row-title { white-space: normal; } .assignments-row select { width: 100%; } .assignments-row-actions { width: 100%; justify-content: flex-end; } }",
  ]
}
